version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directories:
      - '/**'
    schedule:
      interval: 'weekly'
    groups:
      production-dependencies:
        dependency-type: 'production'
        patterns:
          - '*'
      development-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
