// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// AUTO-GENERATED by scripts/generateFileIconTypes.js from src/fileIconTypes.json.
// Do not edit this file manually. Run `npm run generate` to regenerate it.

/**
 * Enumerates special file type icons that do not map to any file extensions.
 * For example, the 'pptx' icon maps to the extensions 'ppt', 'pptm', 'pptx',
 * but the 'folder' icon does not map to any extensions and should be obtained
 * via this enum.
 *
 * Implemented as a `const` object (rather than a TypeScript `enum`) so it does not
 * emit a runtime reverse-mapping. The merged `FileIconType` type below lets it be
 * used as both a value (`FileIconType.folder`) and a type (`type: FileIconType`),
 * preserving the ergonomics of the previous `enum`. Values start at 1 so they evaluate
 * as truthy.
 */
export const FileIconType = {
  docset: 1,
  folder: 2,
  genericFile: 3,
  listItem: 4,
  sharedFolder: 5,
  multiple: 6,
  stream: 7,
  news: 8,
  desktopFolder: 9,
  documentsFolder: 10,
  picturesFolder: 11,
  linkedFolder: 12,
  list: 13,
  form: 14,
  sway: 15,
  playlist: 16,
  loopworkspace: 17,
  planner: 18,
  todoItem: 19,
  portfolio: 20,
  album: 21,
  listForm: 22,
  campaign: 23,
  shortcutsdefaultfolder: 24,
} as const;

export type FileIconType = (typeof FileIconType)[keyof typeof FileIconType];

/**
 * Numeric input form of {@link FileIconType}, accepted by the `type` prop / option.
 * Structurally identical to `FileIconType` (`1 | 2 | … | N`); kept as a named alias
 * for API stability and call-site readability.
 */
export type FileIconTypeInput = FileIconType;

/**
 * Icon base name for each numeric {@link FileIconType} value, positionally indexed by
 * that value (index 0 is unused since values start at 1). Empty entries fall back to the
 * generic file icon at runtime.
 */
export const TYPE_TO_ICON_NAME: ReadonlyArray<string> = [
  '', // 0 (unused)
  'docset', // 1 docset
  'folder', // 2 folder
  '', // 3 genericFile
  'listitem', // 4 listItem
  'sharedfolder', // 5 sharedFolder
  'multiple', // 6 multiple
  'video', // 7 stream
  'sponews', // 8 news
  'desktopfolder', // 9 desktopFolder
  'documentsfolder', // 10 documentsFolder
  'picturesfolder', // 11 picturesFolder
  'linkedfolder', // 12 linkedFolder
  'splist', // 13 list
  'form', // 14 form
  'sway', // 15 sway
  'playlist', // 16 playlist
  'loopworkspace', // 17 loopworkspace
  'planner', // 18 planner
  'todoitem', // 19 todoItem
  'portfolio', // 20 portfolio
  'album', // 21 album
  'listform', // 22 listForm
  'spocampaign', // 23 campaign
  'companyfolder', // 24 shortcutsdefaultfolder
];
