trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)
resources:
  pipelines:
  - pipeline: 'fluentui-system-icons-android-maven-publish'
    project: 'ISS'
    source: 'fluentui-system-icons-android-maven-publish'
  repositories:
  - repository: OfficePipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling-Release
    stages:
    - stage: Stage_1
      displayName: fluentui-system-icons ESRP Release
      jobs:
      - job: Job_1
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: 'fluentui-system-icons-android-maven-publish'
            artifactName: 'aar'
            targetPath: '$(Pipeline.Workspace)/aar'
        steps:
        - task: Bash@3
          displayName: "Print directory structure"
          inputs:
            targetType: "inline"
            script: |
              echo "==== Working Directory Structure ===="
              pwd
              ls -la
              
              echo "==== Pipeline Workspace Structure ===="
              # Fix the variable reference syntax for bash
              PIPELINE_WORKSPACE="$PIPELINE_WORKSPACE"
              echo "Pipeline workspace path: $PIPELINE_WORKSPACE"
              find "$PIPELINE_WORKSPACE" -type f -o -type d 2>/dev/null | sort || echo "Failed to find files in Pipeline Workspace"
              
              echo "==== System Default Working Directory Structure ===="
              # Fix the variable reference syntax for bash
              SYSTEM_DEFAULTWORKINGDIRECTORY="$SYSTEM_DEFAULTWORKINGDIRECTORY"
              echo "Default working directory: $SYSTEM_DEFAULTWORKINGDIRECTORY"
              find "$SYSTEM_DEFAULTWORKINGDIRECTORY" -type f -o -type d 2>/dev/null | sort || echo "Failed to find files in System.DefaultWorkingDirectory"
              
              echo "==== Build.SourcesDirectory Structure ===="
              # Add the Build.SourcesDirectory as an alternative
              BUILD_SOURCESDIRECTORY="$BUILD_SOURCESDIRECTORY"
              echo "Sources directory: $BUILD_SOURCESDIRECTORY"
              find "$BUILD_SOURCESDIRECTORY" -type f -o -type d 2>/dev/null | sort || echo "Failed to find files in Build.SourcesDirectory"
              
              echo "==== Current Directory and Parent Structure ===="
              # Add a more reliable approach using current directory
              find . -type f -o -type d 2>/dev/null | sort
              find .. -maxdepth 2 -type f -o -type d 2>/dev/null | sort
              
              echo "==== Environment Variables ===="
              env | sort
        
        # Add a task to copy artifacts to the expected location
        - task: CopyFiles@2
          displayName: 'Copy files to expected location'
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/aar'
            TargetFolder: '$(System.DefaultWorkingDirectory)/fluentui-system-icons-android-maven-publish/aar'
            CleanTargetFolder: true
            OverWrite: true
        
        # Add a task to verify the files were copied correctly
        - task: Bash@3
          displayName: "Verify artifact location"
          inputs:
            targetType: "inline"
            script: |
              echo "==== Verifying expected ESRP input path ===="
              echo "Expected path: $(System.DefaultWorkingDirectory)/fluentui-system-icons-android-maven-publish/aar"
              
              if [ -d "$(System.DefaultWorkingDirectory)/fluentui-system-icons-android-maven-publish/aar" ]; then
                echo "Directory exists!"
                echo "Contents:"
                find "$(System.DefaultWorkingDirectory)/fluentui-system-icons-android-maven-publish/aar" -type f -o -type d | sort
              else
                echo "Directory does not exist!"
                echo "Creating directory..."
                mkdir -p "$(System.DefaultWorkingDirectory)/fluentui-system-icons-android-maven-publish/aar"
              fi
        
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@9
          displayName: fluentui-system-icons ESRP Release
          inputs:
            connectedservicename: 'ESRP-JSHost3'
            usemanagedidentity: false
            keyvaultname: 'OGX-JSHost-KV'
            authcertname: 'OGX-JSHost-Auth4'
            signcertname: 'OGX-JSHost-Sign3'
            clientid: '0a35e01f-eadf-420a-a2bf-def002ba898d'
            domaintenantid: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            folderlocation: $(System.DefaultWorkingDirectory)/fluentui-system-icons-android-maven-publish/aar
            owners: 'ronakdhoot@microsoft.com'
            approvers: 'dhruvmishra@microsoft.com'