trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)
resources:
  pipelines:
  - pipeline: 'fluentui-system-icons-android-maven-publish'
    project: 'fluentui-native'
    source: 'fluentui-system-icons-android-maven-publish'
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling-Release
    stages:
    - stage: Stage_1
      displayName: fluentui-system-icons ESRP Release
      jobs:
      - job: Job_1
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            buildType: 'specific'
            project: '$(projectName)'
            definition: '$(pipelineDefinition)'
            buildVersionToDownload: 'specific'
            pipelineId: '$(buildId)'
            artifactName: 'aar'
            targetPath: '$(Pipeline.Workspace)/fluentui-system-icons-android-maven-publish/aar'
        steps:
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@7
          displayName: fluentui-system-icons ESRP Release
          inputs:
            connectedservicename: '$(connectedServiceName)'
            keyvaultname: $(keyVaultName)
            authcertname: $(authCertName)
            signcertname: '$(signCertName) '
            clientid: '$(clientId)'
            folderlocation: $(Pipeline.Workspace)/fluentui-system-icons-android-maven-publish/aar
            owners: '$(owners)'
            approvers: '$(approvers)'
            mainpublisher: fluentuiandroidrelease