"use client";
import { createFluentIcon } from '../../util-factory.js';
import sprite from './backpack.svg';
export const BackpackFilled = ( /*#__PURE__*/createFluentIcon('BackpackFilled', "1em", sprite));
export const BackpackRegular = ( /*#__PURE__*/createFluentIcon('BackpackRegular', "1em", sprite));
export const Backpack12Regular = ( /*#__PURE__*/createFluentIcon('Backpack12Regular', "12", sprite));
export const Backpack12Filled = ( /*#__PURE__*/createFluentIcon('Backpack12Filled', "12", sprite));
export const Backpack16Regular = ( /*#__PURE__*/createFluentIcon('Backpack16Regular', "16", sprite));
export const Backpack16Filled = ( /*#__PURE__*/createFluentIcon('Backpack16Filled', "16", sprite));
export const Backpack20Regular = ( /*#__PURE__*/createFluentIcon('Backpack20Regular', "20", sprite));
export const Backpack20Filled = ( /*#__PURE__*/createFluentIcon('Backpack20Filled', "20", sprite));
export const Backpack24Regular = ( /*#__PURE__*/createFluentIcon('Backpack24Regular', "24", sprite));
export const Backpack24Filled = ( /*#__PURE__*/createFluentIcon('Backpack24Filled', "24", sprite));
export const Backpack28Regular = ( /*#__PURE__*/createFluentIcon('Backpack28Regular', "28", sprite));
export const Backpack28Filled = ( /*#__PURE__*/createFluentIcon('Backpack28Filled', "28", sprite));
export const Backpack32Regular = ( /*#__PURE__*/createFluentIcon('Backpack32Regular', "32", sprite));
export const Backpack32Filled = ( /*#__PURE__*/createFluentIcon('Backpack32Filled', "32", sprite));
export const Backpack48Regular = ( /*#__PURE__*/createFluentIcon('Backpack48Regular', "48", sprite));
export const Backpack48Filled = ( /*#__PURE__*/createFluentIcon('Backpack48Filled', "48", sprite));