# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

pool:
  vmImage: 'ubuntu-latest'

name: 1.0.$(Rev:r)

jobs:
- job: build_android
  displayName: Build Android
  steps:
  - template: build-android.yml

- job: build_ios
  displayName: Build iOS
  steps:
  - template: build-ios.yml
    
