import * as React from "react";
import { render } from "react-dom";
import {
    Accessibility28Filled,
Accessibility28Regular,
Add28Filled,
Add28Regular,
AddCircle28Filled,
AddCircle28Regular,
AddSubtractCircle28Filled,
AddSubtractCircle28Regular,
Alert28Filled,
Alert28Regular,
AlertOff28Filled,
AlertOff28Regular,
AlignBottom28Filled,
AlignBottom28Regular,
AlignCenterHorizontal28Filled,
AlignCenterHorizontal28Regular,
AlignCenterVertical28Filled,
AlignCenterVertical28Regular,
AlignLeft28Filled,
AlignLeft28Regular,
AlignRight28Filled,
AlignRight28Regular,
AlignTop28Filled,
AlignTop28Regular,
AnimalCat28Filled,
AnimalCat28Regular,
AnimalRabbit28Filled,
AnimalRabbit28Regular,
AnimalTurtle28Filled,
AnimalTurtle28Regular,
ApprovalsApp28Filled,
ApprovalsApp28Regular,
Apps28Filled,
Apps28Regular,
AppsAddIn28Filled,
AppsAddIn28Regular,
Archive28Filled,
Archive28Regular,
ArrowCounterclockwise28Filled,
ArrowCounterclockwise28Regular,
ArrowCurveDownLeft28Filled,
ArrowCurveDownLeft28Regular,
ArrowDown28Filled,
ArrowDown28Regular,
ArrowHookDownLeft28Filled,
ArrowHookDownLeft28Regular,
ArrowHookDownRight28Filled,
ArrowHookDownRight28Regular,
ArrowHookUpLeft28Filled,
ArrowHookUpLeft28Regular,
ArrowHookUpRight28Filled,
ArrowHookUpRight28Regular,
ArrowLeft28Filled,
ArrowLeft28Regular,
ArrowMaximize28Filled,
ArrowMaximize28Regular,
ArrowMinimize28Filled,
ArrowMinimize28Regular,
ArrowRight28Filled,
ArrowRight28Regular,
ArrowSort28Filled,
ArrowSort28Regular,
ArrowUp28Filled,
ArrowUp28Regular,
Backpack28Filled,
Backpack28Regular,
BackpackAdd28Filled,
BackpackAdd28Regular,
Beach28Filled,
Beach28Regular,
Bluetooth28Filled,
Bluetooth28Regular,
Blur28Filled,
Blur28Regular,
Board28Filled,
Board28Regular,
BoardSplit28Filled,
BoardSplit28Regular,
BookContacts28Filled,
BookContacts28Regular,
BookOpen28Filled,
BookOpen28Regular,
BookOpenMicrophone28Filled,
BookOpenMicrophone28Regular,
Bookmark28Filled,
Bookmark28Regular,
BowlChopsticks28Filled,
BowlChopsticks28Regular,
Briefcase28Filled,
Briefcase28Regular,
BriefcaseOff28Filled,
BriefcaseOff28Regular,
BuildingBank28Filled,
BuildingBank28Regular,
BuildingBankLink28Filled,
BuildingBankLink28Regular,
Calendar3Day28Filled,
Calendar3Day28Regular,
CalendarAgenda28Filled,
CalendarAgenda28Regular,
CalendarCheckmark28Filled,
CalendarCheckmark28Regular,
CalendarDay28Filled,
CalendarDay28Regular,
CalendarEmpty28Filled,
CalendarEmpty28Regular,
CalendarLtr28Filled,
CalendarLtr28Regular,
CalendarMonth28Filled,
CalendarMonth28Regular,
CalendarReply28Filled,
CalendarReply28Regular,
CalendarRtl28Filled,
CalendarRtl28Regular,
CalendarToday28Filled,
CalendarToday28Regular,
CalendarWeekStart28Filled,
CalendarWeekStart28Regular,
Call28Filled,
Call28Regular,
CallEnd28Filled,
CallEnd28Regular,
CallForward28Filled,
CallForward28Regular,
CallInbound28Filled,
CallInbound28Regular,
CallMissed28Filled,
CallMissed28Regular,
CallOutbound28Filled,
CallOutbound28Regular,
CallPark28Filled,
CallPark28Regular,
CallProhibited28Filled,
CallProhibited28Regular,
Camera28Filled,
Camera28Regular,
CameraDome28Filled,
CameraDome28Regular,
Cast28Filled,
Cast28Regular,
Channel28Filled,
Channel28Regular,
ChannelAdd28Filled,
ChannelAdd28Regular,
ChannelAlert28Filled,
ChannelAlert28Regular,
ChannelArrowLeft28Filled,
ChannelArrowLeft28Regular,
ChannelDismiss28Filled,
ChannelDismiss28Regular,
ChannelShare28Filled,
ChannelShare28Regular,
ChartPerson28Filled,
ChartPerson28Regular,
Chat28Filled,
Chat28Regular,
Checkmark28Filled,
Checkmark28Regular,
ChevronDown28Filled,
ChevronDown28Regular,
ChevronLeft28Filled,
ChevronLeft28Regular,
ChevronRight28Filled,
ChevronRight28Regular,
ChevronUp28Filled,
ChevronUp28Regular,
Clock28Filled,
Clock28Regular,
ClosedCaption28Filled,
ClosedCaption28Regular,
ClosedCaptionOff28Filled,
ClosedCaptionOff28Regular,
Cloud28Filled,
Cloud28Regular,
CloudBackup28Filled,
CloudBackup28Regular,
CloudDownload28Filled,
CloudDownload28Regular,
CloudOff28Filled,
CloudOff28Regular,
CloudSync28Filled,
CloudSync28Regular,
CloudSyncComplete28Filled,
CloudSyncComplete28Regular,
Comment28Filled,
Comment28Regular,
CommentAdd28Filled,
CommentAdd28Regular,
CommentArrowLeft28Filled,
CommentArrowLeft28Regular,
CommentArrowRight28Filled,
CommentArrowRight28Regular,
CommentCheckmark28Filled,
CommentCheckmark28Regular,
CommentOff28Filled,
CommentOff28Regular,
CompassNorthwest28Filled,
CompassNorthwest28Regular,
Compose28Filled,
Compose28Regular,
ConferenceRoom28Filled,
ConferenceRoom28Regular,
ContactCard28Filled,
ContactCard28Regular,
ContactCardGroup28Filled,
ContactCardGroup28Regular,
ContractDownLeft28Filled,
ContractDownLeft28Regular,
CursorHover28Filled,
CursorHover28Regular,
CursorHoverOff28Filled,
CursorHoverOff28Regular,
Delete28Filled,
Delete28Regular,
DeleteDismiss28Filled,
DeleteDismiss28Regular,
Dentist28Filled,
Dentist28Regular,
Desktop28Filled,
Desktop28Regular,
DesktopPulse28Filled,
DesktopPulse28Regular,
DeviceMeetingRoom28Filled,
DeviceMeetingRoom28Regular,
DeviceMeetingRoomRemote28Filled,
DeviceMeetingRoomRemote28Regular,
Dismiss28Filled,
Dismiss28Regular,
DismissCircle28Filled,
DismissCircle28Regular,
DockPanelLeft28Filled,
DockPanelLeft28Regular,
DockPanelRight28Filled,
DockPanelRight28Regular,
Doctor28Filled,
Doctor28Regular,
Document28Filled,
Document28Regular,
DocumentAdd28Filled,
DocumentAdd28Regular,
DocumentArrowLeft28Filled,
DocumentArrowLeft28Regular,
DocumentRibbon28Filled,
DocumentRibbon28Regular,
Drop28Filled,
Drop28Regular,
Dumbbell28Filled,
Dumbbell28Regular,
EmojiHand28Filled,
EmojiHand28Regular,
ExpandUpLeft28Filled,
ExpandUpLeft28Regular,
ExpandUpRight28Filled,
ExpandUpRight28Regular,
FStop28Filled,
FStop28Regular,
Filter28Filled,
Filter28Regular,
Flag28Filled,
Flag28Regular,
FlagOff28Filled,
FlagOff28Regular,
FlagPride28Filled,
Flash28Filled,
Flash28Regular,
FlashCheckmark28Filled,
FlashCheckmark28Regular,
Folder28Filled,
Folder28Regular,
FolderAdd28Filled,
FolderAdd28Regular,
FolderArrowRight28Filled,
FolderArrowRight28Regular,
FolderArrowUp28Filled,
FolderArrowUp28Regular,
FolderLink28Filled,
FolderLink28Regular,
FolderProhibited28Filled,
FolderProhibited28Regular,
FontSpaceTrackingIn28Filled,
FontSpaceTrackingIn28Regular,
FontSpaceTrackingOut28Filled,
FontSpaceTrackingOut28Regular,
FormNew28Filled,
FormNew28Regular,
Fps3028Filled,
Fps3028Regular,
Fps6028Filled,
Fps6028Regular,
Glasses28Filled,
Glasses28Regular,
GlassesOff28Filled,
GlassesOff28Regular,
Grid28Filled,
Grid28Regular,
Guest28Filled,
Guest28Regular,
Guitar28Filled,
Guitar28Regular,
HandLeft28Filled,
HandLeft28Regular,
HandRight28Filled,
HandRight28Regular,
Headphones28Filled,
Headphones28Regular,
HeadphonesSoundWave28Filled,
HeadphonesSoundWave28Regular,
Headset28Filled,
Headset28Regular,
Heart28Filled,
Heart28Regular,
Home28Filled,
Home28Regular,
Image28Filled,
Image28Regular,
ImageCopy28Filled,
ImageCopy28Regular,
ImageMultiple28Filled,
ImageMultiple28Regular,
Info28Filled,
Info28Regular,
InprivateAccount28Filled,
InprivateAccount28Regular,
Laptop28Filled,
Laptop28Regular,
Library28Filled,
Library28Regular,
Link28Filled,
Link28Regular,
List28Filled,
List28Regular,
LocalLanguage28Filled,
LocalLanguage28Regular,
Location28Filled,
Location28Regular,
LocationOff28Filled,
LocationOff28Regular,
LockOpen28Filled,
LockOpen28Regular,
Mail28Filled,
Mail28Regular,
MailInbox28Filled,
MailInbox28Regular,
MailInboxAdd28Filled,
MailInboxAdd28Regular,
MailInboxCheckmark28Filled,
MailInboxCheckmark28Regular,
MailInboxDismiss28Filled,
MailInboxDismiss28Regular,
MailRead28Filled,
MailRead28Regular,
MailUnread28Filled,
MailUnread28Regular,
Maximize28Filled,
Maximize28Regular,
MeetNow28Filled,
MeetNow28Regular,
Megaphone28Filled,
Megaphone28Regular,
MicOff28Filled,
MicOff28Regular,
MicOn28Filled,
MicOn28Regular,
MicProhibited28Filled,
MicProhibited28Regular,
Molecule28Filled,
Molecule28Regular,
MoreHorizontal28Filled,
MoreHorizontal28Regular,
MoreVertical28Filled,
MoreVertical28Regular,
Multiplier12X28Filled,
Multiplier12X28Regular,
Multiplier15X28Filled,
Multiplier15X28Regular,
Multiplier18X28Filled,
Multiplier18X28Regular,
Multiplier1X28Filled,
Multiplier1X28Regular,
Multiplier2X28Filled,
Multiplier2X28Regular,
Multiplier5X28Filled,
Multiplier5X28Regular,
News28Filled,
News28Regular,
Notepad28Filled,
Notepad28Regular,
OfficeApps28Filled,
OfficeApps28Regular,
Open28Filled,
Open28Regular,
OpenFolder28Filled,
OpenFolder28Regular,
OpenOff28Filled,
OpenOff28Regular,
Organization28Filled,
Organization28Regular,
Payment28Filled,
Payment28Regular,
People28Filled,
People28Regular,
PeopleCommunity28Filled,
PeopleCommunity28Regular,
PeopleCommunityAdd28Filled,
PeopleCommunityAdd28Regular,
PeopleSwap28Filled,
PeopleSwap28Regular,
PeopleTeam28Filled,
PeopleTeam28Regular,
Person28Filled,
Person28Regular,
PersonAdd28Filled,
PersonAdd28Regular,
PersonMail28Filled,
PersonMail28Regular,
PersonProhibited28Filled,
PersonProhibited28Regular,
PersonTag28Regular,
PhoneDesktop28Filled,
PhoneDesktop28Regular,
PhoneSpanIn28Filled,
PhoneSpanIn28Regular,
PhoneSpanOut28Filled,
PhoneSpanOut28Regular,
Pill28Filled,
Pill28Regular,
Pin28Filled,
Pin28Regular,
PlayCircle28Filled,
PlayCircle28Regular,
PlugDisconnected28Filled,
PlugDisconnected28Regular,
Power28Filled,
Power28Regular,
Premium28Filled,
Premium28Regular,
Prohibited28Filled,
Prohibited28Regular,
Pulse28Filled,
Pulse28Regular,
PuzzleCube28Filled,
PuzzleCube28Regular,
QrCode28Filled,
QrCode28Regular,
Question28Filled,
Question28Regular,
QuestionCircle28Filled,
QuestionCircle28Regular,
QuizNew28Filled,
QuizNew28Regular,
ReadAloud28Filled,
ReadAloud28Regular,
ReadingList28Filled,
ReadingList28Regular,
ReadingListAdd28Filled,
ReadingListAdd28Regular,
Record28Filled,
Record28Regular,
RecordStop28Filled,
RecordStop28Regular,
Rename28Filled,
Rename28Regular,
Search28Filled,
Search28Regular,
Send28Filled,
Send28Regular,
Settings28Filled,
Settings28Regular,
ShareIos28Filled,
ShareIos28Regular,
ShareScreenStart28Filled,
ShareScreenStart28Regular,
ShareScreenStop28Filled,
ShareScreenStop28Regular,
Shield28Filled,
Shield28Regular,
ShieldCheckmark28Filled,
ShieldCheckmark28Regular,
Shifts28Filled,
Shifts28Regular,
Signature28Filled,
Signature28Regular,
SkipBackward1028Filled,
SkipBackward1028Regular,
SkipForward1028Filled,
SkipForward1028Regular,
SkipForward3028Filled,
SkipForward3028Regular,
SlideSearch28Filled,
SlideSearch28Regular,
SlideText28Filled,
SlideText28Regular,
SoundSource28Filled,
SoundSource28Regular,
Speaker028Filled,
Speaker028Regular,
Speaker128Filled,
Speaker128Regular,
Speaker228Filled,
Speaker228Regular,
SpeakerBluetooth28Filled,
SpeakerBluetooth28Regular,
SpeakerMute28Filled,
SpeakerMute28Regular,
SpeakerOff28Filled,
SpeakerOff28Regular,
SpeakerUsb28Filled,
SpeakerUsb28Regular,
SplitHorizontal28Filled,
SplitHorizontal28Regular,
SplitVertical28Filled,
SplitVertical28Regular,
SquareArrowForward28Filled,
SquareArrowForward28Regular,
Star28Filled,
Star28Regular,
StarHalf28Filled,
StarOff28Filled,
StarOff28Regular,
StarOneQuarter28Filled,
StarThreeQuarter28Filled,
Subtract28Filled,
Subtract28Regular,
SubtractCircle28Filled,
SubtractCircle28Regular,
Tab28Filled,
Tab28Regular,
TabInPrivate28Filled,
TabInPrivate28Regular,
Table28Filled,
Table28Regular,
TableSimple28Filled,
TableSimple28Regular,
TasksApp28Filled,
TasksApp28Regular,
Tent28Filled,
Tent28Regular,
TetrisApp28Filled,
TetrisApp28Regular,
TicketDiagonal28Filled,
TicketDiagonal28Regular,
ToggleLeft28Filled,
ToggleLeft28Regular,
ToggleRight28Filled,
ToggleRight28Regular,
Toolbox28Filled,
Toolbox28Regular,
Tv28Filled,
Tv28Regular,
TvUsb28Filled,
TvUsb28Regular,
VehicleCab28Filled,
VehicleCab28Regular,
VehicleCar28Filled,
VehicleCar28Regular,
Video28Filled,
Video28Regular,
VideoOff28Filled,
VideoOff28Regular,
VideoPerson28Filled,
VideoPerson28Regular,
VideoProhibited28Filled,
VideoProhibited28Regular,
Voicemail28Filled,
Voicemail28Regular,
WalkieTalkie28Filled,
WalkieTalkie28Regular,
Wand28Filled,
Wand28Regular,
WeatherMoon28Filled,
WeatherMoon28Regular,
WeatherMoonOff28Filled,
WeatherMoonOff28Regular,

} from "@fluentui/react-icons";

function App() {
	return (
		<div>
			<Accessibility28Filled/>
<Accessibility28Regular/>
<Add28Filled/>
<Add28Regular/>
<AddCircle28Filled/>
<AddCircle28Regular/>
<AddSubtractCircle28Filled/>
<AddSubtractCircle28Regular/>
<Alert28Filled/>
<Alert28Regular/>
<AlertOff28Filled/>
<AlertOff28Regular/>
<AlignBottom28Filled/>
<AlignBottom28Regular/>
<AlignCenterHorizontal28Filled/>
<AlignCenterHorizontal28Regular/>
<AlignCenterVertical28Filled/>
<AlignCenterVertical28Regular/>
<AlignLeft28Filled/>
<AlignLeft28Regular/>
<AlignRight28Filled/>
<AlignRight28Regular/>
<AlignTop28Filled/>
<AlignTop28Regular/>
<AnimalCat28Filled/>
<AnimalCat28Regular/>
<AnimalRabbit28Filled/>
<AnimalRabbit28Regular/>
<AnimalTurtle28Filled/>
<AnimalTurtle28Regular/>
<ApprovalsApp28Filled/>
<ApprovalsApp28Regular/>
<Apps28Filled/>
<Apps28Regular/>
<AppsAddIn28Filled/>
<AppsAddIn28Regular/>
<Archive28Filled/>
<Archive28Regular/>
<ArrowCounterclockwise28Filled/>
<ArrowCounterclockwise28Regular/>
<ArrowCurveDownLeft28Filled/>
<ArrowCurveDownLeft28Regular/>
<ArrowDown28Filled/>
<ArrowDown28Regular/>
<ArrowHookDownLeft28Filled/>
<ArrowHookDownLeft28Regular/>
<ArrowHookDownRight28Filled/>
<ArrowHookDownRight28Regular/>
<ArrowHookUpLeft28Filled/>
<ArrowHookUpLeft28Regular/>
<ArrowHookUpRight28Filled/>
<ArrowHookUpRight28Regular/>
<ArrowLeft28Filled/>
<ArrowLeft28Regular/>
<ArrowMaximize28Filled/>
<ArrowMaximize28Regular/>
<ArrowMinimize28Filled/>
<ArrowMinimize28Regular/>
<ArrowRight28Filled/>
<ArrowRight28Regular/>
<ArrowSort28Filled/>
<ArrowSort28Regular/>
<ArrowUp28Filled/>
<ArrowUp28Regular/>
<Backpack28Filled/>
<Backpack28Regular/>
<BackpackAdd28Filled/>
<BackpackAdd28Regular/>
<Beach28Filled/>
<Beach28Regular/>
<Bluetooth28Filled/>
<Bluetooth28Regular/>
<Blur28Filled/>
<Blur28Regular/>
<Board28Filled/>
<Board28Regular/>
<BoardSplit28Filled/>
<BoardSplit28Regular/>
<BookContacts28Filled/>
<BookContacts28Regular/>
<BookOpen28Filled/>
<BookOpen28Regular/>
<BookOpenMicrophone28Filled/>
<BookOpenMicrophone28Regular/>
<Bookmark28Filled/>
<Bookmark28Regular/>
<BowlChopsticks28Filled/>
<BowlChopsticks28Regular/>
<Briefcase28Filled/>
<Briefcase28Regular/>
<BriefcaseOff28Filled/>
<BriefcaseOff28Regular/>
<BuildingBank28Filled/>
<BuildingBank28Regular/>
<BuildingBankLink28Filled/>
<BuildingBankLink28Regular/>
<Calendar3Day28Filled/>
<Calendar3Day28Regular/>
<CalendarAgenda28Filled/>
<CalendarAgenda28Regular/>
<CalendarCheckmark28Filled/>
<CalendarCheckmark28Regular/>
<CalendarDay28Filled/>
<CalendarDay28Regular/>
<CalendarEmpty28Filled/>
<CalendarEmpty28Regular/>
<CalendarLtr28Filled/>
<CalendarLtr28Regular/>
<CalendarMonth28Filled/>
<CalendarMonth28Regular/>
<CalendarReply28Filled/>
<CalendarReply28Regular/>
<CalendarRtl28Filled/>
<CalendarRtl28Regular/>
<CalendarToday28Filled/>
<CalendarToday28Regular/>
<CalendarWeekStart28Filled/>
<CalendarWeekStart28Regular/>
<Call28Filled/>
<Call28Regular/>
<CallEnd28Filled/>
<CallEnd28Regular/>
<CallForward28Filled/>
<CallForward28Regular/>
<CallInbound28Filled/>
<CallInbound28Regular/>
<CallMissed28Filled/>
<CallMissed28Regular/>
<CallOutbound28Filled/>
<CallOutbound28Regular/>
<CallPark28Filled/>
<CallPark28Regular/>
<CallProhibited28Filled/>
<CallProhibited28Regular/>
<Camera28Filled/>
<Camera28Regular/>
<CameraDome28Filled/>
<CameraDome28Regular/>
<Cast28Filled/>
<Cast28Regular/>
<Channel28Filled/>
<Channel28Regular/>
<ChannelAdd28Filled/>
<ChannelAdd28Regular/>
<ChannelAlert28Filled/>
<ChannelAlert28Regular/>
<ChannelArrowLeft28Filled/>
<ChannelArrowLeft28Regular/>
<ChannelDismiss28Filled/>
<ChannelDismiss28Regular/>
<ChannelShare28Filled/>
<ChannelShare28Regular/>
<ChartPerson28Filled/>
<ChartPerson28Regular/>
<Chat28Filled/>
<Chat28Regular/>
<Checkmark28Filled/>
<Checkmark28Regular/>
<ChevronDown28Filled/>
<ChevronDown28Regular/>
<ChevronLeft28Filled/>
<ChevronLeft28Regular/>
<ChevronRight28Filled/>
<ChevronRight28Regular/>
<ChevronUp28Filled/>
<ChevronUp28Regular/>
<Clock28Filled/>
<Clock28Regular/>
<ClosedCaption28Filled/>
<ClosedCaption28Regular/>
<ClosedCaptionOff28Filled/>
<ClosedCaptionOff28Regular/>
<Cloud28Filled/>
<Cloud28Regular/>
<CloudBackup28Filled/>
<CloudBackup28Regular/>
<CloudDownload28Filled/>
<CloudDownload28Regular/>
<CloudOff28Filled/>
<CloudOff28Regular/>
<CloudSync28Filled/>
<CloudSync28Regular/>
<CloudSyncComplete28Filled/>
<CloudSyncComplete28Regular/>
<Comment28Filled/>
<Comment28Regular/>
<CommentAdd28Filled/>
<CommentAdd28Regular/>
<CommentArrowLeft28Filled/>
<CommentArrowLeft28Regular/>
<CommentArrowRight28Filled/>
<CommentArrowRight28Regular/>
<CommentCheckmark28Filled/>
<CommentCheckmark28Regular/>
<CommentOff28Filled/>
<CommentOff28Regular/>
<CompassNorthwest28Filled/>
<CompassNorthwest28Regular/>
<Compose28Filled/>
<Compose28Regular/>
<ConferenceRoom28Filled/>
<ConferenceRoom28Regular/>
<ContactCard28Filled/>
<ContactCard28Regular/>
<ContactCardGroup28Filled/>
<ContactCardGroup28Regular/>
<ContractDownLeft28Filled/>
<ContractDownLeft28Regular/>
<CursorHover28Filled/>
<CursorHover28Regular/>
<CursorHoverOff28Filled/>
<CursorHoverOff28Regular/>
<Delete28Filled/>
<Delete28Regular/>
<DeleteDismiss28Filled/>
<DeleteDismiss28Regular/>
<Dentist28Filled/>
<Dentist28Regular/>
<Desktop28Filled/>
<Desktop28Regular/>
<DesktopPulse28Filled/>
<DesktopPulse28Regular/>
<DeviceMeetingRoom28Filled/>
<DeviceMeetingRoom28Regular/>
<DeviceMeetingRoomRemote28Filled/>
<DeviceMeetingRoomRemote28Regular/>
<Dismiss28Filled/>
<Dismiss28Regular/>
<DismissCircle28Filled/>
<DismissCircle28Regular/>
<DockPanelLeft28Filled/>
<DockPanelLeft28Regular/>
<DockPanelRight28Filled/>
<DockPanelRight28Regular/>
<Doctor28Filled/>
<Doctor28Regular/>
<Document28Filled/>
<Document28Regular/>
<DocumentAdd28Filled/>
<DocumentAdd28Regular/>
<DocumentArrowLeft28Filled/>
<DocumentArrowLeft28Regular/>
<DocumentRibbon28Filled/>
<DocumentRibbon28Regular/>
<Drop28Filled/>
<Drop28Regular/>
<Dumbbell28Filled/>
<Dumbbell28Regular/>
<EmojiHand28Filled/>
<EmojiHand28Regular/>
<ExpandUpLeft28Filled/>
<ExpandUpLeft28Regular/>
<ExpandUpRight28Filled/>
<ExpandUpRight28Regular/>
<FStop28Filled/>
<FStop28Regular/>
<Filter28Filled/>
<Filter28Regular/>
<Flag28Filled/>
<Flag28Regular/>
<FlagOff28Filled/>
<FlagOff28Regular/>
<FlagPride28Filled/>
<Flash28Filled/>
<Flash28Regular/>
<FlashCheckmark28Filled/>
<FlashCheckmark28Regular/>
<Folder28Filled/>
<Folder28Regular/>
<FolderAdd28Filled/>
<FolderAdd28Regular/>
<FolderArrowRight28Filled/>
<FolderArrowRight28Regular/>
<FolderArrowUp28Filled/>
<FolderArrowUp28Regular/>
<FolderLink28Filled/>
<FolderLink28Regular/>
<FolderProhibited28Filled/>
<FolderProhibited28Regular/>
<FontSpaceTrackingIn28Filled/>
<FontSpaceTrackingIn28Regular/>
<FontSpaceTrackingOut28Filled/>
<FontSpaceTrackingOut28Regular/>
<FormNew28Filled/>
<FormNew28Regular/>
<Fps3028Filled/>
<Fps3028Regular/>
<Fps6028Filled/>
<Fps6028Regular/>
<Glasses28Filled/>
<Glasses28Regular/>
<GlassesOff28Filled/>
<GlassesOff28Regular/>
<Grid28Filled/>
<Grid28Regular/>
<Guest28Filled/>
<Guest28Regular/>
<Guitar28Filled/>
<Guitar28Regular/>
<HandLeft28Filled/>
<HandLeft28Regular/>
<HandRight28Filled/>
<HandRight28Regular/>
<Headphones28Filled/>
<Headphones28Regular/>
<HeadphonesSoundWave28Filled/>
<HeadphonesSoundWave28Regular/>
<Headset28Filled/>
<Headset28Regular/>
<Heart28Filled/>
<Heart28Regular/>
<Home28Filled/>
<Home28Regular/>
<Image28Filled/>
<Image28Regular/>
<ImageCopy28Filled/>
<ImageCopy28Regular/>
<ImageMultiple28Filled/>
<ImageMultiple28Regular/>
<Info28Filled/>
<Info28Regular/>
<InprivateAccount28Filled/>
<InprivateAccount28Regular/>
<Laptop28Filled/>
<Laptop28Regular/>
<Library28Filled/>
<Library28Regular/>
<Link28Filled/>
<Link28Regular/>
<List28Filled/>
<List28Regular/>
<LocalLanguage28Filled/>
<LocalLanguage28Regular/>
<Location28Filled/>
<Location28Regular/>
<LocationOff28Filled/>
<LocationOff28Regular/>
<LockOpen28Filled/>
<LockOpen28Regular/>
<Mail28Filled/>
<Mail28Regular/>
<MailInbox28Filled/>
<MailInbox28Regular/>
<MailInboxAdd28Filled/>
<MailInboxAdd28Regular/>
<MailInboxCheckmark28Filled/>
<MailInboxCheckmark28Regular/>
<MailInboxDismiss28Filled/>
<MailInboxDismiss28Regular/>
<MailRead28Filled/>
<MailRead28Regular/>
<MailUnread28Filled/>
<MailUnread28Regular/>
<Maximize28Filled/>
<Maximize28Regular/>
<MeetNow28Filled/>
<MeetNow28Regular/>
<Megaphone28Filled/>
<Megaphone28Regular/>
<MicOff28Filled/>
<MicOff28Regular/>
<MicOn28Filled/>
<MicOn28Regular/>
<MicProhibited28Filled/>
<MicProhibited28Regular/>
<Molecule28Filled/>
<Molecule28Regular/>
<MoreHorizontal28Filled/>
<MoreHorizontal28Regular/>
<MoreVertical28Filled/>
<MoreVertical28Regular/>
<Multiplier12X28Filled/>
<Multiplier12X28Regular/>
<Multiplier15X28Filled/>
<Multiplier15X28Regular/>
<Multiplier18X28Filled/>
<Multiplier18X28Regular/>
<Multiplier1X28Filled/>
<Multiplier1X28Regular/>
<Multiplier2X28Filled/>
<Multiplier2X28Regular/>
<Multiplier5X28Filled/>
<Multiplier5X28Regular/>
<News28Filled/>
<News28Regular/>
<Notepad28Filled/>
<Notepad28Regular/>
<OfficeApps28Filled/>
<OfficeApps28Regular/>
<Open28Filled/>
<Open28Regular/>
<OpenFolder28Filled/>
<OpenFolder28Regular/>
<OpenOff28Filled/>
<OpenOff28Regular/>
<Organization28Filled/>
<Organization28Regular/>
<Payment28Filled/>
<Payment28Regular/>
<People28Filled/>
<People28Regular/>
<PeopleCommunity28Filled/>
<PeopleCommunity28Regular/>
<PeopleCommunityAdd28Filled/>
<PeopleCommunityAdd28Regular/>
<PeopleSwap28Filled/>
<PeopleSwap28Regular/>
<PeopleTeam28Filled/>
<PeopleTeam28Regular/>
<Person28Filled/>
<Person28Regular/>
<PersonAdd28Filled/>
<PersonAdd28Regular/>
<PersonMail28Filled/>
<PersonMail28Regular/>
<PersonProhibited28Filled/>
<PersonProhibited28Regular/>
<PersonTag28Regular/>
<PhoneDesktop28Filled/>
<PhoneDesktop28Regular/>
<PhoneSpanIn28Filled/>
<PhoneSpanIn28Regular/>
<PhoneSpanOut28Filled/>
<PhoneSpanOut28Regular/>
<Pill28Filled/>
<Pill28Regular/>
<Pin28Filled/>
<Pin28Regular/>
<PlayCircle28Filled/>
<PlayCircle28Regular/>
<PlugDisconnected28Filled/>
<PlugDisconnected28Regular/>
<Power28Filled/>
<Power28Regular/>
<Premium28Filled/>
<Premium28Regular/>
<Prohibited28Filled/>
<Prohibited28Regular/>
<Pulse28Filled/>
<Pulse28Regular/>
<PuzzleCube28Filled/>
<PuzzleCube28Regular/>
<QrCode28Filled/>
<QrCode28Regular/>
<Question28Filled/>
<Question28Regular/>
<QuestionCircle28Filled/>
<QuestionCircle28Regular/>
<QuizNew28Filled/>
<QuizNew28Regular/>
<ReadAloud28Filled/>
<ReadAloud28Regular/>
<ReadingList28Filled/>
<ReadingList28Regular/>
<ReadingListAdd28Filled/>
<ReadingListAdd28Regular/>
<Record28Filled/>
<Record28Regular/>
<RecordStop28Filled/>
<RecordStop28Regular/>
<Rename28Filled/>
<Rename28Regular/>
<Search28Filled/>
<Search28Regular/>
<Send28Filled/>
<Send28Regular/>
<Settings28Filled/>
<Settings28Regular/>
<ShareIos28Filled/>
<ShareIos28Regular/>
<ShareScreenStart28Filled/>
<ShareScreenStart28Regular/>
<ShareScreenStop28Filled/>
<ShareScreenStop28Regular/>
<Shield28Filled/>
<Shield28Regular/>
<ShieldCheckmark28Filled/>
<ShieldCheckmark28Regular/>
<Shifts28Filled/>
<Shifts28Regular/>
<Signature28Filled/>
<Signature28Regular/>
<SkipBackward1028Filled/>
<SkipBackward1028Regular/>
<SkipForward1028Filled/>
<SkipForward1028Regular/>
<SkipForward3028Filled/>
<SkipForward3028Regular/>
<SlideSearch28Filled/>
<SlideSearch28Regular/>
<SlideText28Filled/>
<SlideText28Regular/>
<SoundSource28Filled/>
<SoundSource28Regular/>
<Speaker028Filled/>
<Speaker028Regular/>
<Speaker128Filled/>
<Speaker128Regular/>
<Speaker228Filled/>
<Speaker228Regular/>
<SpeakerBluetooth28Filled/>
<SpeakerBluetooth28Regular/>
<SpeakerMute28Filled/>
<SpeakerMute28Regular/>
<SpeakerOff28Filled/>
<SpeakerOff28Regular/>
<SpeakerUsb28Filled/>
<SpeakerUsb28Regular/>
<SplitHorizontal28Filled/>
<SplitHorizontal28Regular/>
<SplitVertical28Filled/>
<SplitVertical28Regular/>
<SquareArrowForward28Filled/>
<SquareArrowForward28Regular/>
<Star28Filled/>
<Star28Regular/>
<StarHalf28Filled/>
<StarOff28Filled/>
<StarOff28Regular/>
<StarOneQuarter28Filled/>
<StarThreeQuarter28Filled/>
<Subtract28Filled/>
<Subtract28Regular/>
<SubtractCircle28Filled/>
<SubtractCircle28Regular/>
<Tab28Filled/>
<Tab28Regular/>
<TabInPrivate28Filled/>
<TabInPrivate28Regular/>
<Table28Filled/>
<Table28Regular/>
<TableSimple28Filled/>
<TableSimple28Regular/>
<TasksApp28Filled/>
<TasksApp28Regular/>
<Tent28Filled/>
<Tent28Regular/>
<TetrisApp28Filled/>
<TetrisApp28Regular/>
<TicketDiagonal28Filled/>
<TicketDiagonal28Regular/>
<ToggleLeft28Filled/>
<ToggleLeft28Regular/>
<ToggleRight28Filled/>
<ToggleRight28Regular/>
<Toolbox28Filled/>
<Toolbox28Regular/>
<Tv28Filled/>
<Tv28Regular/>
<TvUsb28Filled/>
<TvUsb28Regular/>
<VehicleCab28Filled/>
<VehicleCab28Regular/>
<VehicleCar28Filled/>
<VehicleCar28Regular/>
<Video28Filled/>
<Video28Regular/>
<VideoOff28Filled/>
<VideoOff28Regular/>
<VideoPerson28Filled/>
<VideoPerson28Regular/>
<VideoProhibited28Filled/>
<VideoProhibited28Regular/>
<Voicemail28Filled/>
<Voicemail28Regular/>
<WalkieTalkie28Filled/>
<WalkieTalkie28Regular/>
<Wand28Filled/>
<Wand28Regular/>
<WeatherMoon28Filled/>
<WeatherMoon28Regular/>
<WeatherMoonOff28Filled/>
<WeatherMoonOff28Regular/>
        </div >
    );
}

const rootElement = document.getElementById("root");
render(<App />, rootElement);