import * as React from "react";
import { render } from "react-dom";
import {
    AddSubtractCircle48Filled,
AddSubtractCircle48Regular,
AlignBottom48Filled,
AlignBottom48Regular,
AlignCenterHorizontal48Filled,
AlignCenterHorizontal48Regular,
AlignCenterVertical48Filled,
AlignCenterVertical48Regular,
AlignLeft48Filled,
AlignLeft48Regular,
AlignRight48Filled,
AlignRight48Regular,
AlignTop48Filled,
AlignTop48Regular,
Archive48Filled,
Archive48Regular,
ArrowCircleDown48Filled,
ArrowCircleDown48Regular,
ArrowCircleLeft48Filled,
ArrowCircleLeft48Regular,
ArrowCircleRight48Filled,
ArrowCircleRight48Regular,
ArrowCircleUp48Filled,
ArrowCircleUp48Regular,
ArrowClockwise48Filled,
ArrowClockwise48Regular,
ArrowCounterclockwise48Filled,
ArrowCounterclockwise48Regular,
ArrowDown48Filled,
ArrowDown48Regular,
ArrowDownload48Filled,
ArrowDownload48Regular,
ArrowForward48Filled,
ArrowForward48Regular,
ArrowLeft48Filled,
ArrowLeft48Regular,
ArrowRedo48Filled,
ArrowRedo48Regular,
ArrowReply48Filled,
ArrowReply48Regular,
ArrowReplyAll48Filled,
ArrowReplyAll48Regular,
ArrowRight48Filled,
ArrowRight48Regular,
ArrowUndo48Filled,
ArrowUndo48Regular,
ArrowUp48Filled,
ArrowUp48Regular,
Backpack48Filled,
Backpack48Regular,
BackpackAdd48Filled,
BackpackAdd48Regular,
BoardSplit48Filled,
BoardSplit48Regular,
BookOpen48Filled,
BookOpen48Regular,
BookOpenMicrophone48Filled,
BookOpenMicrophone48Regular,
Briefcase48Filled,
Briefcase48Regular,
BriefcaseOff48Filled,
BriefcaseOff48Regular,
BuildingBank48Filled,
BuildingBank48Regular,
BuildingBankLink48Filled,
BuildingBankLink48Regular,
CallForward48Filled,
CallForward48Regular,
CallInbound48Filled,
CallInbound48Regular,
CallMissed48Filled,
CallMissed48Regular,
CallOutbound48Filled,
CallOutbound48Regular,
CallPark48Filled,
CallPark48Regular,
CallProhibited48Filled,
CallProhibited48Regular,
CameraAdd48Filled,
CameraAdd48Regular,
CameraDome48Filled,
CameraDome48Regular,
Channel48Filled,
Channel48Regular,
ChannelAdd48Filled,
ChannelAdd48Regular,
ChannelAlert48Filled,
ChannelAlert48Regular,
ChannelArrowLeft48Filled,
ChannelArrowLeft48Regular,
ChannelDismiss48Filled,
ChannelDismiss48Regular,
ChannelShare48Filled,
ChannelShare48Regular,
ChannelSubtract48Filled,
ChannelSubtract48Regular,
ChartPerson48Filled,
ChartPerson48Regular,
Chat48Filled,
Chat48Regular,
Checkmark48Filled,
Checkmark48Regular,
CheckmarkCircle48Filled,
CheckmarkCircle48Regular,
ChevronDown48Filled,
ChevronDown48Regular,
ChevronLeft48Filled,
ChevronLeft48Regular,
ChevronRight48Filled,
ChevronRight48Regular,
ChevronUp48Filled,
ChevronUp48Regular,
Clock48Filled,
Clock48Regular,
ClosedCaption48Filled,
ClosedCaption48Regular,
ClosedCaptionOff48Filled,
ClosedCaptionOff48Regular,
Cloud48Filled,
Cloud48Regular,
CloudArrowDown48Filled,
CloudArrowDown48Regular,
CloudArrowUp48Filled,
CloudArrowUp48Regular,
CloudBackup48Filled,
CloudBackup48Regular,
CloudCheckmark48Filled,
CloudCheckmark48Regular,
CloudDismiss48Filled,
CloudDismiss48Regular,
CloudDownload48Filled,
CloudDownload48Regular,
CloudOff48Filled,
CloudOff48Regular,
CloudSync48Filled,
CloudSync48Regular,
CloudSyncComplete48Filled,
CloudSyncComplete48Regular,
CloudWords48Filled,
CloudWords48Regular,
Comment48Filled,
Comment48Regular,
CommentAdd48Filled,
CommentAdd48Regular,
CommentArrowLeft48Filled,
CommentArrowLeft48Regular,
CommentArrowRight48Filled,
CommentArrowRight48Regular,
CommentCheckmark48Filled,
CommentCheckmark48Regular,
CommentOff48Filled,
CommentOff48Regular,
ConferenceRoom48Filled,
ConferenceRoom48Regular,
ContactCard48Filled,
ContactCard48Regular,
ContactCardGroup48Filled,
ContactCardGroup48Regular,
ContractDownLeft48Filled,
ContractDownLeft48Regular,
CursorHover48Filled,
CursorHover48Regular,
CursorHoverOff48Filled,
CursorHoverOff48Regular,
Delete48Filled,
Delete48Regular,
Dentist48Filled,
Dentist48Regular,
DesktopPulse48Filled,
DesktopPulse48Regular,
DeviceMeetingRoom48Filled,
DeviceMeetingRoom48Regular,
DeviceMeetingRoomRemote48Filled,
DeviceMeetingRoomRemote48Regular,
Dialpad48Filled,
Dialpad48Regular,
Dismiss48Filled,
Dismiss48Regular,
DismissCircle48Filled,
DismissCircle48Regular,
Diversity48Filled,
Diversity48Regular,
DockPanelLeft48Filled,
DockPanelLeft48Regular,
DockPanelRight48Filled,
DockPanelRight48Regular,
Doctor48Filled,
Doctor48Regular,
Document48Filled,
Document48Regular,
DocumentAdd48Filled,
DocumentAdd48Regular,
DocumentArrowLeft48Filled,
DocumentArrowLeft48Regular,
DocumentCopy48Filled,
DocumentCopy48Regular,
DocumentRibbon48Filled,
DocumentRibbon48Regular,
Drop48Filled,
Drop48Regular,
ExpandUpLeft48Filled,
ExpandUpLeft48Regular,
ExpandUpRight48Filled,
ExpandUpRight48Regular,
Fingerprint48Filled,
Fingerprint48Regular,
Flag48Filled,
Flag48Regular,
FlagOff48Filled,
FlagOff48Regular,
FlagPride48Filled,
Fluent48Filled,
Fluent48Regular,
Folder48Filled,
Folder48Regular,
FolderAdd48Filled,
FolderAdd48Regular,
FolderArrowRight48Filled,
FolderArrowRight48Regular,
FolderArrowUp48Filled,
FolderArrowUp48Regular,
FolderLink48Filled,
FolderLink48Regular,
FolderProhibited48Filled,
FolderProhibited48Regular,
FormNew48Filled,
FormNew48Regular,
Fps3048Filled,
Fps3048Regular,
Fps6048Filled,
Fps6048Regular,
Glasses48Filled,
Glasses48Regular,
GlassesOff48Filled,
GlassesOff48Regular,
GlobeVideo48Filled,
GlobeVideo48Regular,
Guardian48Filled,
Guardian48Regular,
Headphones48Filled,
Headphones48Regular,
HeadphonesSoundWave48Filled,
HeadphonesSoundWave48Regular,
Headset48Filled,
Headset48Regular,
Home48Filled,
Home48Regular,
Image48Filled,
Image48Regular,
Link48Filled,
Link48Regular,
Location48Filled,
Location48Regular,
LocationArrowLeft48Filled,
LocationArrowLeft48Regular,
LocationArrowRight48Filled,
LocationArrowRight48Regular,
LocationArrowUp48Filled,
LocationArrowUp48Regular,
LocationOff48Filled,
LocationOff48Regular,
LockShield48Filled,
LockShield48Regular,
Mail48Filled,
Mail48Regular,
MailRead48Filled,
MailRead48Regular,
MailUnread48Filled,
MailUnread48Regular,
Maximize48Filled,
Maximize48Regular,
MeetNow48Filled,
MeetNow48Regular,
MicOff48Filled,
MicOff48Regular,
MicOn48Filled,
MicOn48Regular,
MicProhibited48Filled,
MicProhibited48Regular,
Molecule48Filled,
Molecule48Regular,
MoreHorizontal48Filled,
MoreHorizontal48Regular,
MoreVertical48Filled,
MoreVertical48Regular,
Multiplier12X48Filled,
Multiplier12X48Regular,
Multiplier15X48Filled,
Multiplier15X48Regular,
Multiplier18X48Filled,
Multiplier18X48Regular,
Multiplier1X48Filled,
Multiplier1X48Regular,
Multiplier2X48Filled,
Multiplier2X48Regular,
Multiplier5X48Filled,
Multiplier5X48Regular,
Open48Filled,
Open48Regular,
OpenFolder48Filled,
OpenFolder48Regular,
OpenOff48Filled,
OpenOff48Regular,
Options48Filled,
Options48Regular,
Organization48Filled,
Organization48Regular,
PanelLeft48Filled,
PanelLeft48Regular,
PanelRight48Filled,
PanelRight48Regular,
Pause48Filled,
Pause48Regular,
Person48Filled,
Person48Regular,
PersonMail48Filled,
PersonMail48Regular,
PersonTag48Regular,
Pin48Filled,
Pin48Regular,
PinOff48Filled,
PinOff48Regular,
Play48Filled,
Play48Regular,
Print48Filled,
Print48Regular,
Prohibited48Filled,
Prohibited48Regular,
PuzzleCube48Filled,
PuzzleCube48Regular,
Question48Filled,
Question48Regular,
QuestionCircle48Filled,
QuestionCircle48Regular,
QuizNew48Filled,
QuizNew48Regular,
Record48Filled,
Record48Regular,
RecordStop48Filled,
RecordStop48Regular,
RoadCone48Filled,
RoadCone48Regular,
ScanThumbUp48Filled,
ScanThumbUp48Regular,
ScreenShareStart48Filled,
ScreenShareStart48Regular,
Search48Filled,
Search48Regular,
Share48Filled,
Share48Regular,
ShareIos48Filled,
ShareIos48Regular,
ShareScreenStop48Filled,
ShareScreenStop48Regular,
Shield48Filled,
Shield48Regular,
ShieldCheckmark48Filled,
ShieldCheckmark48Regular,
ShieldTask48Filled,
ShieldTask48Regular,
ShieldVideo48Filled,
ShieldVideo48Regular,
SkipBackward1048Filled,
SkipBackward1048Regular,
SkipForward1048Filled,
SkipForward1048Regular,
SkipForward3048Filled,
SkipForward3048Regular,
SlideText48Filled,
SlideText48Regular,
Speaker048Filled,
Speaker048Regular,
Speaker148Filled,
Speaker148Regular,
Speaker248Filled,
Speaker248Regular,
SpeakerMute48Filled,
SpeakerMute48Regular,
SpeakerOff48Filled,
SpeakerOff48Regular,
SplitHorizontal48Filled,
SplitHorizontal48Regular,
SplitVertical48Filled,
SplitVertical48Regular,
SquareArrowForward48Filled,
SquareArrowForward48Regular,
Subtract48Filled,
Subtract48Regular,
Table48Filled,
Table48Regular,
TableSimple48Filled,
TableSimple48Regular,
Tent48Filled,
Tent48Regular,
TetrisApp48Filled,
TetrisApp48Regular,
ToggleLeft48Filled,
ToggleLeft48Regular,
ToggleRight48Filled,
ToggleRight48Regular,
Tv48Filled,
Tv48Regular,
TvUsb48Filled,
TvUsb48Regular,
VehicleCar48Filled,
VehicleCar48Regular,
VehicleCarCollision48Filled,
VehicleCarCollision48Regular,
Video48Filled,
Video48Regular,
VideoPerson48Filled,
VideoPerson48Regular,
Wand48Filled,
Wand48Regular,
WeatherBlowingSnow48Filled,
WeatherBlowingSnow48Regular,
WeatherCloudy48Filled,
WeatherCloudy48Regular,
WeatherDrizzle48Filled,
WeatherDrizzle48Regular,
WeatherDuststorm48Filled,
WeatherDuststorm48Regular,
WeatherFog48Filled,
WeatherFog48Regular,
WeatherHailDay48Filled,
WeatherHailDay48Regular,
WeatherHailNight48Filled,
WeatherHailNight48Regular,
WeatherHaze48Filled,
WeatherHaze48Regular,
WeatherMoon48Filled,
WeatherMoon48Regular,
WeatherMoonOff48Filled,
WeatherMoonOff48Regular,
WeatherPartlyCloudyDay48Filled,
WeatherPartlyCloudyDay48Regular,
WeatherPartlyCloudyNight48Filled,
WeatherPartlyCloudyNight48Regular,
WeatherRain48Filled,
WeatherRain48Regular,
WeatherRainShowersDay48Filled,
WeatherRainShowersDay48Regular,
WeatherRainShowersNight48Filled,
WeatherRainShowersNight48Regular,
WeatherRainSnow48Filled,
WeatherRainSnow48Regular,
WeatherSnow48Filled,
WeatherSnow48Regular,
WeatherSnowShowerDay48Filled,
WeatherSnowShowerDay48Regular,
WeatherSnowShowerNight48Filled,
WeatherSnowShowerNight48Regular,
WeatherSnowflake48Filled,
WeatherSnowflake48Regular,
WeatherSqualls48Filled,
WeatherSqualls48Regular,
WeatherSunny48Filled,
WeatherSunny48Regular,
WeatherSunnyHigh48Filled,
WeatherSunnyHigh48Regular,
WeatherSunnyLow48Filled,
WeatherSunnyLow48Regular,
WeatherThunderstorm48Filled,
WeatherThunderstorm48Regular,
Whiteboard48Filled,
Whiteboard48Regular,

} from "@fluentui/react-icons";

function App() {
	return (
		<div>
			<AddSubtractCircle48Filled/>
<AddSubtractCircle48Regular/>
<AlignBottom48Filled/>
<AlignBottom48Regular/>
<AlignCenterHorizontal48Filled/>
<AlignCenterHorizontal48Regular/>
<AlignCenterVertical48Filled/>
<AlignCenterVertical48Regular/>
<AlignLeft48Filled/>
<AlignLeft48Regular/>
<AlignRight48Filled/>
<AlignRight48Regular/>
<AlignTop48Filled/>
<AlignTop48Regular/>
<Archive48Filled/>
<Archive48Regular/>
<ArrowCircleDown48Filled/>
<ArrowCircleDown48Regular/>
<ArrowCircleLeft48Filled/>
<ArrowCircleLeft48Regular/>
<ArrowCircleRight48Filled/>
<ArrowCircleRight48Regular/>
<ArrowCircleUp48Filled/>
<ArrowCircleUp48Regular/>
<ArrowClockwise48Filled/>
<ArrowClockwise48Regular/>
<ArrowCounterclockwise48Filled/>
<ArrowCounterclockwise48Regular/>
<ArrowDown48Filled/>
<ArrowDown48Regular/>
<ArrowDownload48Filled/>
<ArrowDownload48Regular/>
<ArrowForward48Filled/>
<ArrowForward48Regular/>
<ArrowLeft48Filled/>
<ArrowLeft48Regular/>
<ArrowRedo48Filled/>
<ArrowRedo48Regular/>
<ArrowReply48Filled/>
<ArrowReply48Regular/>
<ArrowReplyAll48Filled/>
<ArrowReplyAll48Regular/>
<ArrowRight48Filled/>
<ArrowRight48Regular/>
<ArrowUndo48Filled/>
<ArrowUndo48Regular/>
<ArrowUp48Filled/>
<ArrowUp48Regular/>
<Backpack48Filled/>
<Backpack48Regular/>
<BackpackAdd48Filled/>
<BackpackAdd48Regular/>
<BoardSplit48Filled/>
<BoardSplit48Regular/>
<BookOpen48Filled/>
<BookOpen48Regular/>
<BookOpenMicrophone48Filled/>
<BookOpenMicrophone48Regular/>
<Briefcase48Filled/>
<Briefcase48Regular/>
<BriefcaseOff48Filled/>
<BriefcaseOff48Regular/>
<BuildingBank48Filled/>
<BuildingBank48Regular/>
<BuildingBankLink48Filled/>
<BuildingBankLink48Regular/>
<CallForward48Filled/>
<CallForward48Regular/>
<CallInbound48Filled/>
<CallInbound48Regular/>
<CallMissed48Filled/>
<CallMissed48Regular/>
<CallOutbound48Filled/>
<CallOutbound48Regular/>
<CallPark48Filled/>
<CallPark48Regular/>
<CallProhibited48Filled/>
<CallProhibited48Regular/>
<CameraAdd48Filled/>
<CameraAdd48Regular/>
<CameraDome48Filled/>
<CameraDome48Regular/>
<Channel48Filled/>
<Channel48Regular/>
<ChannelAdd48Filled/>
<ChannelAdd48Regular/>
<ChannelAlert48Filled/>
<ChannelAlert48Regular/>
<ChannelArrowLeft48Filled/>
<ChannelArrowLeft48Regular/>
<ChannelDismiss48Filled/>
<ChannelDismiss48Regular/>
<ChannelShare48Filled/>
<ChannelShare48Regular/>
<ChannelSubtract48Filled/>
<ChannelSubtract48Regular/>
<ChartPerson48Filled/>
<ChartPerson48Regular/>
<Chat48Filled/>
<Chat48Regular/>
<Checkmark48Filled/>
<Checkmark48Regular/>
<CheckmarkCircle48Filled/>
<CheckmarkCircle48Regular/>
<ChevronDown48Filled/>
<ChevronDown48Regular/>
<ChevronLeft48Filled/>
<ChevronLeft48Regular/>
<ChevronRight48Filled/>
<ChevronRight48Regular/>
<ChevronUp48Filled/>
<ChevronUp48Regular/>
<Clock48Filled/>
<Clock48Regular/>
<ClosedCaption48Filled/>
<ClosedCaption48Regular/>
<ClosedCaptionOff48Filled/>
<ClosedCaptionOff48Regular/>
<Cloud48Filled/>
<Cloud48Regular/>
<CloudArrowDown48Filled/>
<CloudArrowDown48Regular/>
<CloudArrowUp48Filled/>
<CloudArrowUp48Regular/>
<CloudBackup48Filled/>
<CloudBackup48Regular/>
<CloudCheckmark48Filled/>
<CloudCheckmark48Regular/>
<CloudDismiss48Filled/>
<CloudDismiss48Regular/>
<CloudDownload48Filled/>
<CloudDownload48Regular/>
<CloudOff48Filled/>
<CloudOff48Regular/>
<CloudSync48Filled/>
<CloudSync48Regular/>
<CloudSyncComplete48Filled/>
<CloudSyncComplete48Regular/>
<CloudWords48Filled/>
<CloudWords48Regular/>
<Comment48Filled/>
<Comment48Regular/>
<CommentAdd48Filled/>
<CommentAdd48Regular/>
<CommentArrowLeft48Filled/>
<CommentArrowLeft48Regular/>
<CommentArrowRight48Filled/>
<CommentArrowRight48Regular/>
<CommentCheckmark48Filled/>
<CommentCheckmark48Regular/>
<CommentOff48Filled/>
<CommentOff48Regular/>
<ConferenceRoom48Filled/>
<ConferenceRoom48Regular/>
<ContactCard48Filled/>
<ContactCard48Regular/>
<ContactCardGroup48Filled/>
<ContactCardGroup48Regular/>
<ContractDownLeft48Filled/>
<ContractDownLeft48Regular/>
<CursorHover48Filled/>
<CursorHover48Regular/>
<CursorHoverOff48Filled/>
<CursorHoverOff48Regular/>
<Delete48Filled/>
<Delete48Regular/>
<Dentist48Filled/>
<Dentist48Regular/>
<DesktopPulse48Filled/>
<DesktopPulse48Regular/>
<DeviceMeetingRoom48Filled/>
<DeviceMeetingRoom48Regular/>
<DeviceMeetingRoomRemote48Filled/>
<DeviceMeetingRoomRemote48Regular/>
<Dialpad48Filled/>
<Dialpad48Regular/>
<Dismiss48Filled/>
<Dismiss48Regular/>
<DismissCircle48Filled/>
<DismissCircle48Regular/>
<Diversity48Filled/>
<Diversity48Regular/>
<DockPanelLeft48Filled/>
<DockPanelLeft48Regular/>
<DockPanelRight48Filled/>
<DockPanelRight48Regular/>
<Doctor48Filled/>
<Doctor48Regular/>
<Document48Filled/>
<Document48Regular/>
<DocumentAdd48Filled/>
<DocumentAdd48Regular/>
<DocumentArrowLeft48Filled/>
<DocumentArrowLeft48Regular/>
<DocumentCopy48Filled/>
<DocumentCopy48Regular/>
<DocumentRibbon48Filled/>
<DocumentRibbon48Regular/>
<Drop48Filled/>
<Drop48Regular/>
<ExpandUpLeft48Filled/>
<ExpandUpLeft48Regular/>
<ExpandUpRight48Filled/>
<ExpandUpRight48Regular/>
<Fingerprint48Filled/>
<Fingerprint48Regular/>
<Flag48Filled/>
<Flag48Regular/>
<FlagOff48Filled/>
<FlagOff48Regular/>
<FlagPride48Filled/>
<Fluent48Filled/>
<Fluent48Regular/>
<Folder48Filled/>
<Folder48Regular/>
<FolderAdd48Filled/>
<FolderAdd48Regular/>
<FolderArrowRight48Filled/>
<FolderArrowRight48Regular/>
<FolderArrowUp48Filled/>
<FolderArrowUp48Regular/>
<FolderLink48Filled/>
<FolderLink48Regular/>
<FolderProhibited48Filled/>
<FolderProhibited48Regular/>
<FormNew48Filled/>
<FormNew48Regular/>
<Fps3048Filled/>
<Fps3048Regular/>
<Fps6048Filled/>
<Fps6048Regular/>
<Glasses48Filled/>
<Glasses48Regular/>
<GlassesOff48Filled/>
<GlassesOff48Regular/>
<GlobeVideo48Filled/>
<GlobeVideo48Regular/>
<Guardian48Filled/>
<Guardian48Regular/>
<Headphones48Filled/>
<Headphones48Regular/>
<HeadphonesSoundWave48Filled/>
<HeadphonesSoundWave48Regular/>
<Headset48Filled/>
<Headset48Regular/>
<Home48Filled/>
<Home48Regular/>
<Image48Filled/>
<Image48Regular/>
<Link48Filled/>
<Link48Regular/>
<Location48Filled/>
<Location48Regular/>
<LocationArrowLeft48Filled/>
<LocationArrowLeft48Regular/>
<LocationArrowRight48Filled/>
<LocationArrowRight48Regular/>
<LocationArrowUp48Filled/>
<LocationArrowUp48Regular/>
<LocationOff48Filled/>
<LocationOff48Regular/>
<LockShield48Filled/>
<LockShield48Regular/>
<Mail48Filled/>
<Mail48Regular/>
<MailRead48Filled/>
<MailRead48Regular/>
<MailUnread48Filled/>
<MailUnread48Regular/>
<Maximize48Filled/>
<Maximize48Regular/>
<MeetNow48Filled/>
<MeetNow48Regular/>
<MicOff48Filled/>
<MicOff48Regular/>
<MicOn48Filled/>
<MicOn48Regular/>
<MicProhibited48Filled/>
<MicProhibited48Regular/>
<Molecule48Filled/>
<Molecule48Regular/>
<MoreHorizontal48Filled/>
<MoreHorizontal48Regular/>
<MoreVertical48Filled/>
<MoreVertical48Regular/>
<Multiplier12X48Filled/>
<Multiplier12X48Regular/>
<Multiplier15X48Filled/>
<Multiplier15X48Regular/>
<Multiplier18X48Filled/>
<Multiplier18X48Regular/>
<Multiplier1X48Filled/>
<Multiplier1X48Regular/>
<Multiplier2X48Filled/>
<Multiplier2X48Regular/>
<Multiplier5X48Filled/>
<Multiplier5X48Regular/>
<Open48Filled/>
<Open48Regular/>
<OpenFolder48Filled/>
<OpenFolder48Regular/>
<OpenOff48Filled/>
<OpenOff48Regular/>
<Options48Filled/>
<Options48Regular/>
<Organization48Filled/>
<Organization48Regular/>
<PanelLeft48Filled/>
<PanelLeft48Regular/>
<PanelRight48Filled/>
<PanelRight48Regular/>
<Pause48Filled/>
<Pause48Regular/>
<Person48Filled/>
<Person48Regular/>
<PersonMail48Filled/>
<PersonMail48Regular/>
<PersonTag48Regular/>
<Pin48Filled/>
<Pin48Regular/>
<PinOff48Filled/>
<PinOff48Regular/>
<Play48Filled/>
<Play48Regular/>
<Print48Filled/>
<Print48Regular/>
<Prohibited48Filled/>
<Prohibited48Regular/>
<PuzzleCube48Filled/>
<PuzzleCube48Regular/>
<Question48Filled/>
<Question48Regular/>
<QuestionCircle48Filled/>
<QuestionCircle48Regular/>
<QuizNew48Filled/>
<QuizNew48Regular/>
<Record48Filled/>
<Record48Regular/>
<RecordStop48Filled/>
<RecordStop48Regular/>
<RoadCone48Filled/>
<RoadCone48Regular/>
<ScanThumbUp48Filled/>
<ScanThumbUp48Regular/>
<ScreenShareStart48Filled/>
<ScreenShareStart48Regular/>
<Search48Filled/>
<Search48Regular/>
<Share48Filled/>
<Share48Regular/>
<ShareIos48Filled/>
<ShareIos48Regular/>
<ShareScreenStop48Filled/>
<ShareScreenStop48Regular/>
<Shield48Filled/>
<Shield48Regular/>
<ShieldCheckmark48Filled/>
<ShieldCheckmark48Regular/>
<ShieldTask48Filled/>
<ShieldTask48Regular/>
<ShieldVideo48Filled/>
<ShieldVideo48Regular/>
<SkipBackward1048Filled/>
<SkipBackward1048Regular/>
<SkipForward1048Filled/>
<SkipForward1048Regular/>
<SkipForward3048Filled/>
<SkipForward3048Regular/>
<SlideText48Filled/>
<SlideText48Regular/>
<Speaker048Filled/>
<Speaker048Regular/>
<Speaker148Filled/>
<Speaker148Regular/>
<Speaker248Filled/>
<Speaker248Regular/>
<SpeakerMute48Filled/>
<SpeakerMute48Regular/>
<SpeakerOff48Filled/>
<SpeakerOff48Regular/>
<SplitHorizontal48Filled/>
<SplitHorizontal48Regular/>
<SplitVertical48Filled/>
<SplitVertical48Regular/>
<SquareArrowForward48Filled/>
<SquareArrowForward48Regular/>
<Subtract48Filled/>
<Subtract48Regular/>
<Table48Filled/>
<Table48Regular/>
<TableSimple48Filled/>
<TableSimple48Regular/>
<Tent48Filled/>
<Tent48Regular/>
<TetrisApp48Filled/>
<TetrisApp48Regular/>
<ToggleLeft48Filled/>
<ToggleLeft48Regular/>
<ToggleRight48Filled/>
<ToggleRight48Regular/>
<Tv48Filled/>
<Tv48Regular/>
<TvUsb48Filled/>
<TvUsb48Regular/>
<VehicleCar48Filled/>
<VehicleCar48Regular/>
<VehicleCarCollision48Filled/>
<VehicleCarCollision48Regular/>
<Video48Filled/>
<Video48Regular/>
<VideoPerson48Filled/>
<VideoPerson48Regular/>
<Wand48Filled/>
<Wand48Regular/>
<WeatherBlowingSnow48Filled/>
<WeatherBlowingSnow48Regular/>
<WeatherCloudy48Filled/>
<WeatherCloudy48Regular/>
<WeatherDrizzle48Filled/>
<WeatherDrizzle48Regular/>
<WeatherDuststorm48Filled/>
<WeatherDuststorm48Regular/>
<WeatherFog48Filled/>
<WeatherFog48Regular/>
<WeatherHailDay48Filled/>
<WeatherHailDay48Regular/>
<WeatherHailNight48Filled/>
<WeatherHailNight48Regular/>
<WeatherHaze48Filled/>
<WeatherHaze48Regular/>
<WeatherMoon48Filled/>
<WeatherMoon48Regular/>
<WeatherMoonOff48Filled/>
<WeatherMoonOff48Regular/>
<WeatherPartlyCloudyDay48Filled/>
<WeatherPartlyCloudyDay48Regular/>
<WeatherPartlyCloudyNight48Filled/>
<WeatherPartlyCloudyNight48Regular/>
<WeatherRain48Filled/>
<WeatherRain48Regular/>
<WeatherRainShowersDay48Filled/>
<WeatherRainShowersDay48Regular/>
<WeatherRainShowersNight48Filled/>
<WeatherRainShowersNight48Regular/>
<WeatherRainSnow48Filled/>
<WeatherRainSnow48Regular/>
<WeatherSnow48Filled/>
<WeatherSnow48Regular/>
<WeatherSnowShowerDay48Filled/>
<WeatherSnowShowerDay48Regular/>
<WeatherSnowShowerNight48Filled/>
<WeatherSnowShowerNight48Regular/>
<WeatherSnowflake48Filled/>
<WeatherSnowflake48Regular/>
<WeatherSqualls48Filled/>
<WeatherSqualls48Regular/>
<WeatherSunny48Filled/>
<WeatherSunny48Regular/>
<WeatherSunnyHigh48Filled/>
<WeatherSunnyHigh48Regular/>
<WeatherSunnyLow48Filled/>
<WeatherSunnyLow48Regular/>
<WeatherThunderstorm48Filled/>
<WeatherThunderstorm48Regular/>
<Whiteboard48Filled/>
<Whiteboard48Regular/>
        </div >
    );
}

const rootElement = document.getElementById("root");
render(<App />, rootElement);