import * as React from "react";
import { render } from "react-dom";
import {
    Accessibility16Filled,
Accessibility16Regular,
Add16Filled,
Add16Regular,
AddCircle16Filled,
AddCircle16Regular,
AddSquareMultiple16Filled,
AddSquareMultiple16Regular,
AddSubtractCircle16Filled,
AddSubtractCircle16Regular,
AirplaneTakeOff16Filled,
AirplaneTakeOff16Regular,
Alert16Filled,
Alert16Regular,
AlertOff16Filled,
AlertOff16Regular,
AlertUrgent16Filled,
AlertUrgent16Regular,
AlignBottom16Filled,
AlignBottom16Regular,
AlignCenterHorizontal16Filled,
AlignCenterHorizontal16Regular,
AlignCenterVertical16Filled,
AlignCenterVertical16Regular,
AlignLeft16Filled,
AlignLeft16Regular,
AlignRight16Filled,
AlignRight16Regular,
AlignTop16Filled,
AlignTop16Regular,
AnimalRabbit16Filled,
AnimalRabbit16Regular,
AnimalTurtle16Filled,
AnimalTurtle16Regular,
ApprovalsApp16Filled,
ApprovalsApp16Regular,
Apps16Filled,
Apps16Regular,
AppsAddIn16Filled,
AppsAddIn16Regular,
Archive16Filled,
Archive16Regular,
ArrowBounce16Filled,
ArrowBounce16Regular,
ArrowCircleDownRight16Filled,
ArrowCircleDownRight16Regular,
ArrowCircleUp16Filled,
ArrowCircleUp16Regular,
ArrowCurveDownLeft16Filled,
ArrowCurveDownLeft16Regular,
ArrowDown16Filled,
ArrowDown16Regular,
ArrowDownLeft16Filled,
ArrowDownLeft16Regular,
ArrowDownload16Filled,
ArrowDownload16Regular,
ArrowForward16Filled,
ArrowForward16Regular,
ArrowHookDownLeft16Filled,
ArrowHookDownLeft16Regular,
ArrowHookDownRight16Filled,
ArrowHookDownRight16Regular,
ArrowHookUpLeft16Filled,
ArrowHookUpLeft16Regular,
ArrowHookUpRight16Filled,
ArrowHookUpRight16Regular,
ArrowMaximize16Filled,
ArrowMaximize16Regular,
ArrowMinimize16Filled,
ArrowMinimize16Regular,
ArrowRepeatAll16Filled,
ArrowRepeatAll16Regular,
ArrowRepeatAllOff16Filled,
ArrowRepeatAllOff16Regular,
ArrowReply16Filled,
ArrowReply16Regular,
ArrowReplyAll16Filled,
ArrowReplyAll16Regular,
ArrowReplyDown16Filled,
ArrowReplyDown16Regular,
ArrowRight16Filled,
ArrowRight16Regular,
ArrowStepBack16Filled,
ArrowStepBack16Regular,
ArrowStepIn16Filled,
ArrowStepIn16Regular,
ArrowStepOut16Filled,
ArrowStepOut16Regular,
ArrowStepOver16Filled,
ArrowStepOver16Regular,
ArrowSync16Filled,
ArrowSync16Regular,
ArrowSyncCircle16Filled,
ArrowSyncCircle16Regular,
ArrowTrending16Filled,
ArrowTrending16Regular,
ArrowUndo16Filled,
ArrowUndo16Regular,
ArrowUpLeft16Filled,
ArrowUpLeft16Regular,
ArrowUpRight16Filled,
ArrowUpRight16Regular,
ArrowUpload16Filled,
ArrowUpload16Regular,
Attach16Filled,
Attach16Regular,
Backpack16Filled,
Backpack16Regular,
Balloon16Filled,
Balloon16Regular,
Beach16Filled,
Beach16Regular,
Beaker16Filled,
Beaker16Regular,
Bed16Filled,
Bed16Regular,
Block16Filled,
Block16Regular,
Blur16Filled,
Blur16Regular,
Board16Filled,
Board16Regular,
BoardSplit16Filled,
BoardSplit16Regular,
BookNumber16Filled,
BookNumber16Regular,
Bookmark16Filled,
Bookmark16Regular,
BranchCompare16Filled,
BranchCompare16Regular,
BranchFork16Filled,
BranchFork16Regular,
BriefcaseOff16Filled,
BriefcaseOff16Regular,
Bug16Filled,
Bug16Regular,
Building16Filled,
Building16Regular,
BuildingBank16Filled,
BuildingBank16Regular,
BuildingBankLink16Filled,
BuildingBankLink16Regular,
BuildingShop16Filled,
BuildingShop16Regular,
BuildingSkyscraper16Filled,
BuildingSkyscraper16Regular,
CalendarCancel16Filled,
CalendarCancel16Regular,
CalendarCheckmark16Filled,
CalendarCheckmark16Regular,
CalendarClock16Filled,
CalendarClock16Regular,
CalendarEdit16Filled,
CalendarEdit16Regular,
CalendarEmpty16Filled,
CalendarEmpty16Regular,
CalendarLtr16Filled,
CalendarLtr16Regular,
CalendarMail16Filled,
CalendarMail16Regular,
CalendarQuestionMark16Filled,
CalendarQuestionMark16Regular,
CalendarReply16Filled,
CalendarReply16Regular,
CalendarRtl16Filled,
CalendarRtl16Regular,
CalendarSync16Filled,
CalendarSync16Regular,
CalendarToday16Filled,
CalendarToday16Regular,
CalendarWorkWeek16Filled,
CalendarWorkWeek16Regular,
Call16Filled,
Call16Regular,
CallForward16Filled,
CallForward16Regular,
CallInbound16Filled,
CallInbound16Regular,
CallMissed16Filled,
CallMissed16Regular,
CallOutbound16Filled,
CallOutbound16Regular,
CallPark16Filled,
CallPark16Regular,
CallProhibited16Filled,
CallProhibited16Regular,
Camera16Filled,
Camera16Regular,
Caret16Filled,
Caret16Regular,
CaretDown16Filled,
CaretDown16Regular,
CaretDownLeft16Filled,
CaretDownLeft16Regular,
CaretLeft16Filled,
CaretLeft16Regular,
CaretRight16Filled,
CaretRight16Regular,
CaretUp16Filled,
CaretUp16Regular,
Cart16Filled,
Cart16Regular,
Channel16Filled,
Channel16Regular,
ChannelAdd16Filled,
ChannelAdd16Regular,
ChannelAlert16Filled,
ChannelAlert16Regular,
ChannelArrowLeft16Filled,
ChannelArrowLeft16Regular,
ChannelDismiss16Filled,
ChannelDismiss16Regular,
ChannelShare16Filled,
ChannelShare16Regular,
Chat16Filled,
Chat16Regular,
CheckboxUnchecked16Filled,
CheckboxUnchecked16Regular,
Checkmark16Filled,
Checkmark16Regular,
CheckmarkCircle16Filled,
CheckmarkCircle16Regular,
CheckmarkLock16Filled,
CheckmarkLock16Regular,
CheckmarkUnderlineCircle16Filled,
CheckmarkUnderlineCircle16Regular,
ChevronDoubleUp16Filled,
ChevronDoubleUp16Regular,
ChevronDown16Filled,
ChevronDown16Regular,
ChevronLeft16Filled,
ChevronLeft16Regular,
ChevronRight16Filled,
ChevronRight16Regular,
ChevronUp16Filled,
ChevronUp16Regular,
Circle16Filled,
Circle16Regular,
City16Filled,
City16Regular,
Classification16Filled,
Classification16Regular,
Clipboard16Filled,
Clipboard16Regular,
ClipboardArrowRight16Filled,
ClipboardArrowRight16Regular,
ClipboardCode16Filled,
ClipboardCode16Regular,
ClipboardLetter16Filled,
ClipboardLetter16Regular,
ClipboardLink16Filled,
ClipboardLink16Regular,
ClipboardPaste16Filled,
ClipboardPaste16Regular,
Clock16Filled,
Clock16Regular,
ClosedCaption16Filled,
ClosedCaption16Regular,
ClosedCaptionOff16Filled,
ClosedCaptionOff16Regular,
Cloud16Filled,
Cloud16Regular,
CloudBackup16Filled,
CloudBackup16Regular,
CloudDownload16Filled,
CloudDownload16Regular,
CloudOff16Filled,
CloudOff16Regular,
CloudSync16Filled,
CloudSync16Regular,
CloudSyncComplete16Filled,
CloudSyncComplete16Regular,
ColorLine16Filled,
ColorLine16Regular,
ColorLineAccent16Regular,
Comment16Filled,
Comment16Regular,
CommentAdd16Filled,
CommentAdd16Regular,
CommentArrowLeft16Filled,
CommentArrowLeft16Regular,
CommentArrowRight16Filled,
CommentArrowRight16Regular,
CommentCheckmark16Filled,
CommentCheckmark16Regular,
CommentMention16Filled,
CommentMention16Regular,
CommentMultiple16Filled,
CommentMultiple16Regular,
CommentOff16Filled,
CommentOff16Regular,
Communication16Filled,
Communication16Regular,
CompassNorthwest16Filled,
CompassNorthwest16Regular,
Compose16Filled,
Compose16Regular,
ConferenceRoom16Filled,
ConferenceRoom16Regular,
Connector16Filled,
Connector16Regular,
ContactCardGroup16Filled,
ContactCardGroup16Regular,
ContentSettings16Filled,
ContentSettings16Regular,
Copy16Filled,
Copy16Regular,
CopyArrowRight16Filled,
CopyArrowRight16Regular,
Cube16Filled,
Cube16Regular,
CurrencyDollarEuro16Filled,
CurrencyDollarEuro16Regular,
CurrencyDollarRupee16Filled,
CurrencyDollarRupee16Regular,
CursorHover16Filled,
CursorHover16Regular,
CursorHoverOff16Filled,
CursorHoverOff16Regular,
Delete16Filled,
Delete16Regular,
Dentist16Filled,
Dentist16Regular,
DesignIdeas16Filled,
DesignIdeas16Regular,
Desktop16Filled,
Desktop16Regular,
DesktopArrowRight16Filled,
DesktopArrowRight16Regular,
DesktopMac16Filled,
DesktopMac16Regular,
DesktopPulse16Filled,
DesktopPulse16Regular,
Dismiss16Filled,
Dismiss16Regular,
DismissCircle16Filled,
DismissCircle16Regular,
DismissSquareMultiple16Filled,
DismissSquareMultiple16Regular,
DockPanelLeft16Filled,
DockPanelLeft16Regular,
DockPanelRight16Filled,
DockPanelRight16Regular,
Doctor16Filled,
Doctor16Regular,
Document16Filled,
Document16Regular,
DocumentAdd16Filled,
DocumentAdd16Regular,
DocumentArrowLeft16Filled,
DocumentArrowLeft16Regular,
DocumentCatchUp16Filled,
DocumentCatchUp16Regular,
DocumentCopy16Filled,
DocumentCopy16Regular,
DocumentEdit16Filled,
DocumentEdit16Regular,
DocumentError16Filled,
DocumentError16Regular,
DocumentFooter16Filled,
DocumentFooter16Regular,
DocumentHeader16Filled,
DocumentHeader16Regular,
DocumentHeaderArrowDown16Filled,
DocumentHeaderArrowDown16Regular,
DocumentHeaderFooter16Filled,
DocumentHeaderFooter16Regular,
DocumentPdf16Filled,
DocumentPdf16Regular,
DocumentQuestionMark16Filled,
DocumentQuestionMark16Regular,
DocumentRibbon16Filled,
DocumentRibbon16Regular,
DoorArrowLeft16Filled,
DoorArrowLeft16Regular,
Drafts16Filled,
Drafts16Regular,
DrinkBeer16Filled,
DrinkBeer16Regular,
DrinkCoffee16Filled,
DrinkCoffee16Regular,
DrinkMargarita16Filled,
DrinkMargarita16Regular,
DrinkWine16Filled,
DrinkWine16Regular,
Drop16Filled,
Drop16Regular,
Dumbbell16Filled,
Dumbbell16Regular,
Earth16Filled,
Earth16Regular,
Edit16Filled,
Edit16Regular,
EditOff16Filled,
EditOff16Regular,
Emoji16Filled,
Emoji16Regular,
EmojiAdd16Filled,
EmojiAdd16Regular,
ErrorCircle16Filled,
ErrorCircle16Regular,
EyeShow16Filled,
EyeShow16Regular,
EyeTrackingOff16Filled,
EyeTrackingOff16Regular,
EyeTrackingOn16Filled,
EyeTrackingOn16Regular,
FStop16Filled,
FStop16Regular,
Filter16Filled,
Filter16Regular,
Flag16Filled,
Flag16Regular,
FlagOff16Filled,
FlagOff16Regular,
FlagPride16Filled,
Flash16Filled,
Flash16Regular,
FlashCheckmark16Filled,
FlashCheckmark16Regular,
Folder16Filled,
Folder16Regular,
FolderArrowRight16Filled,
FolderArrowRight16Regular,
FolderArrowUp16Filled,
FolderArrowUp16Regular,
FolderMail16Filled,
FolderMail16Regular,
FolderOpen16Filled,
FolderOpen16Regular,
FolderProhibited16Filled,
FolderProhibited16Regular,
FolderSwap16Filled,
FolderSwap16Regular,
FolderSync16Filled,
FolderSync16Regular,
FolderZip16Filled,
FolderZip16Regular,
FontSpaceTrackingIn16Filled,
FontSpaceTrackingIn16Regular,
FontSpaceTrackingOut16Filled,
FontSpaceTrackingOut16Regular,
FoodEgg16Filled,
FoodEgg16Regular,
FoodToast16Filled,
FoodToast16Regular,
Fps3016Filled,
Fps3016Regular,
Fps6016Filled,
Fps6016Regular,
Glasses16Filled,
Glasses16Regular,
GlassesOff16Filled,
GlassesOff16Regular,
Globe16Filled,
Globe16Regular,
Grid16Filled,
Grid16Regular,
Guest16Filled,
Guest16Regular,
Guitar16Filled,
Guitar16Regular,
HandLeft16Filled,
HandLeft16Regular,
HandRight16Filled,
HandRight16Regular,
Handshake16Filled,
Handshake16Regular,
HatGraduation16Filled,
HatGraduation16Regular,
Hd16Filled,
Hd16Regular,
Headset16Filled,
Headset16Regular,
Heart16Filled,
Heart16Regular,
Highlight16Filled,
Highlight16Regular,
HighlightAccent16Filled,
Home16Filled,
Home16Regular,
HomeCheckmark16Filled,
HomeCheckmark16Regular,
Image16Filled,
Image16Regular,
ImageEdit16Filled,
ImageEdit16Regular,
Important16Filled,
Important16Regular,
Info16Filled,
Info16Regular,
InkingTool16Filled,
InkingTool16Regular,
InkingToolAccent16Filled,
InprivateAccount16Filled,
InprivateAccount16Regular,
Javascript16Filled,
Javascript16Regular,
Key16Filled,
Key16Regular,
KeyCommand16Filled,
KeyCommand16Regular,
KeyboardShift16Filled,
KeyboardShift16Regular,
Laptop16Filled,
Laptop16Regular,
LeafOne16Filled,
LeafOne16Regular,
LeafThree16Filled,
LeafThree16Regular,
LeafTwo16Filled,
LeafTwo16Regular,
Library16Filled,
Library16Regular,
Lightbulb16Filled,
Lightbulb16Regular,
LightbulbFilament16Filled,
LightbulbFilament16Regular,
Likert16Filled,
Likert16Regular,
Link16Filled,
Link16Regular,
LinkEdit16Filled,
LinkEdit16Regular,
LinkSquare16Filled,
LinkSquare16Regular,
List16Filled,
List16Regular,
LocalLanguage16Filled,
LocalLanguage16Regular,
Location16Filled,
Location16Regular,
LocationOff16Filled,
LocationOff16Regular,
LockClosed16Filled,
LockClosed16Regular,
Mail16Filled,
Mail16Regular,
MailAll16Filled,
MailAll16Regular,
MailDismiss16Filled,
MailDismiss16Regular,
MailInbox16Filled,
MailInbox16Regular,
MailInboxAdd16Filled,
MailInboxAdd16Regular,
MailInboxCheckmark16Filled,
MailInboxCheckmark16Regular,
MailInboxDismiss16Filled,
MailInboxDismiss16Regular,
MailProhibited16Filled,
MailProhibited16Regular,
MailRead16Filled,
MailRead16Regular,
MailUnread16Filled,
MailUnread16Regular,
MapDrive16Filled,
MapDrive16Regular,
MathFormula16Filled,
MathFormula16Regular,
Maximize16Filled,
Maximize16Regular,
MeetNow16Filled,
MeetNow16Regular,
Megaphone16Filled,
Megaphone16Regular,
Mention16Filled,
Mention16Regular,
MicOff16Filled,
MicOff16Regular,
MicOn16Filled,
MicOn16Regular,
MicProhibited16Filled,
MicProhibited16Regular,
MicSparkle16Filled,
MicSparkle16Regular,
Money16Filled,
Money16Regular,
MoreHorizontal16Filled,
MoreHorizontal16Regular,
MoreVertical16Filled,
MoreVertical16Regular,
MoviesAndTv16Filled,
MoviesAndTv16Regular,
MusicNote216Filled,
MusicNote216Regular,
MyLocation16Filled,
MyLocation16Regular,
New16Filled,
New16Regular,
Next16Filled,
Next16Regular,
NoteAdd16Filled,
NoteAdd16Regular,
NumberRow16Filled,
NumberRow16Regular,
NumberSymbol16Filled,
NumberSymbol16Regular,
Open16Filled,
Open16Regular,
OpenFolder16Filled,
OpenFolder16Regular,
OpenOff16Filled,
OpenOff16Regular,
Options16Filled,
Options16Regular,
PageFit16Filled,
PageFit16Regular,
PaintBrush16Filled,
PaintBrush16Regular,
PaintBucket16Filled,
PaintBucket16Regular,
PaneClose16Filled,
PaneClose16Regular,
PaneOpen16Filled,
PaneOpen16Regular,
Pause16Filled,
Pause16Regular,
Payment16Filled,
Payment16Regular,
People16Filled,
People16Regular,
PeopleAdd16Filled,
PeopleAdd16Regular,
PeopleCall16Filled,
PeopleCall16Regular,
PeopleCommunity16Filled,
PeopleCommunity16Regular,
PeopleError16Filled,
PeopleError16Regular,
PeopleProhibited16Filled,
PeopleProhibited16Regular,
PeopleSwap16Filled,
PeopleSwap16Regular,
PeopleTeam16Filled,
PeopleTeam16Regular,
Person16Filled,
Person16Regular,
PersonAdd16Filled,
PersonAdd16Regular,
PersonArrowRight16Filled,
PersonArrowRight16Regular,
PersonAvailable16Filled,
PersonAvailable16Regular,
PersonBoard16Filled,
PersonBoard16Regular,
PersonCall16Filled,
PersonCall16Regular,
PersonClock16Filled,
PersonClock16Regular,
PersonDelete16Filled,
PersonDelete16Regular,
PersonMail16Filled,
PersonMail16Regular,
PersonProhibited16Filled,
PersonProhibited16Regular,
PersonQuestionMark16Filled,
PersonQuestionMark16Regular,
PersonSupport16Filled,
PersonSupport16Regular,
PersonSwap16Filled,
PersonSwap16Regular,
PhoneDesktop16Filled,
PhoneDesktop16Regular,
PhoneLaptop16Filled,
PhoneLaptop16Regular,
PhoneSpanIn16Filled,
PhoneSpanIn16Regular,
PhoneSpanOut16Filled,
PhoneSpanOut16Regular,
PictureInPicture16Filled,
PictureInPicture16Regular,
Pin16Filled,
Pin16Regular,
PinOff16Filled,
PinOff16Regular,
PlayCircle16Filled,
PlayCircle16Regular,
Premium16Filled,
Premium16Regular,
PresenceAvailable16Filled,
PresenceAvailable16Regular,
PresenceAway16Filled,
PresenceBlocked16Regular,
PresenceBusy16Filled,
PresenceDnd16Filled,
PresenceDnd16Regular,
PresenceOffline16Regular,
PresenceOof16Regular,
PresenceUnknown16Regular,
PreviewLink16Filled,
PreviewLink16Regular,
Previous16Filled,
Previous16Regular,
ProhibitedMultiple16Filled,
ProhibitedMultiple16Regular,
ProtocolHandler16Filled,
ProtocolHandler16Regular,
PuzzleCube16Filled,
PuzzleCube16Regular,
Question16Filled,
Question16Regular,
QuestionCircle16Filled,
QuestionCircle16Regular,
RatingMature16Filled,
RatingMature16Regular,
ReOrder16Filled,
ReOrder16Regular,
ReOrderDotsHorizontal16Filled,
ReOrderDotsHorizontal16Regular,
ReOrderDotsVertical16Filled,
ReOrderDotsVertical16Regular,
ReadAloud16Filled,
ReadAloud16Regular,
ReadingList16Filled,
ReadingList16Regular,
ReadingListAdd16Filled,
ReadingListAdd16Regular,
Record16Filled,
Record16Regular,
Remote16Filled,
Remote16Regular,
Rename16Filled,
Rename16Regular,
ResizeLarge16Filled,
ResizeLarge16Regular,
ResizeSmall16Filled,
ResizeSmall16Regular,
Restore16Filled,
Restore16Regular,
Reward16Filled,
Reward16Regular,
Ribbon16Filled,
Ribbon16Regular,
Rocket16Filled,
Rocket16Regular,
Ruler16Filled,
Ruler16Regular,
Run16Filled,
Run16Regular,
Savings16Filled,
Savings16Regular,
ScaleFit16Filled,
ScaleFit16Regular,
Search16Filled,
Search16Regular,
SearchVisual16Filled,
SearchVisual16Regular,
Send16Filled,
Send16Regular,
SerialPort16Filled,
SerialPort16Regular,
SetTopStack16Filled,
SetTopStack16Regular,
Settings16Filled,
Settings16Regular,
ShapeExclude16Filled,
ShapeExclude16Regular,
ShapeIntersect16Filled,
ShapeIntersect16Regular,
ShapeSubtract16Filled,
ShapeSubtract16Regular,
ShapeUnion16Filled,
ShapeUnion16Regular,
Shapes16Filled,
Shapes16Regular,
ShareScreenStop16Filled,
ShareScreenStop16Regular,
Shield16Filled,
Shield16Regular,
ShieldCheckmark16Filled,
ShieldCheckmark16Regular,
ShieldDismiss16Filled,
ShieldDismiss16Regular,
ShieldKeyhole16Filled,
ShieldKeyhole16Regular,
Shifts16Filled,
Shifts16Regular,
Signature16Filled,
Signature16Regular,
Signed16Filled,
Signed16Regular,
Sim16Filled,
Sim16Regular,
SlideText16Filled,
SlideText16Regular,
Snooze16Filled,
Snooze16Regular,
Speaker016Filled,
Speaker016Regular,
Speaker116Filled,
Speaker116Regular,
Speaker216Filled,
Speaker216Regular,
SpeakerEdit16Filled,
SpeakerEdit16Regular,
SpeakerMute16Filled,
SpeakerMute16Regular,
SpeakerOff16Filled,
SpeakerOff16Regular,
SplitHorizontal16Filled,
SplitHorizontal16Regular,
SplitVertical16Filled,
SplitVertical16Regular,
Sport16Filled,
Sport16Regular,
SquareArrowForward16Filled,
SquareArrowForward16Regular,
Star16Filled,
Star16Regular,
StarAdd16Filled,
StarAdd16Regular,
StarHalf16Filled,
StarOff16Filled,
StarOff16Regular,
StarOneQuarter16Filled,
StarProhibited16Filled,
StarProhibited16Regular,
StarThreeQuarter16Filled,
Status16Filled,
Status16Regular,
Stop16Filled,
Stop16Regular,
StoreMicrosoft16Filled,
StoreMicrosoft16Regular,
StrikethroughGaNa16Filled,
StrikethroughGaNa16Regular,
Subtract16Filled,
Subtract16Regular,
SubtractSquareMultiple16Filled,
SubtractSquareMultiple16Regular,
Symbols16Filled,
Symbols16Regular,
SyncOff16Filled,
SyncOff16Regular,
Tab16Filled,
Tab16Regular,
TabDesktopArrowClockwise16Filled,
TabDesktopArrowClockwise16Regular,
TabDesktopImage16Filled,
TabDesktopImage16Regular,
TabInPrivate16Filled,
TabInPrivate16Regular,
Table16Filled,
Table16Regular,
TableSimple16Filled,
TableSimple16Regular,
Tag16Filled,
Tag16Regular,
TagQuestionMark16Filled,
TagQuestionMark16Regular,
Target16Filled,
Target16Regular,
TargetEdit16Filled,
TargetEdit16Regular,
Tent16Filled,
Tent16Regular,
TetrisApp16Filled,
TetrisApp16Regular,
TextBold16Filled,
TextBold16Regular,
TextBulletListSquareWarning16Filled,
TextBulletListSquareWarning16Regular,
TextBulletListTree16Filled,
TextBulletListTree16Regular,
TextColor16Filled,
TextColor16Regular,
TextColorAccent16Regular,
TextField16Filled,
TextField16Regular,
TextFont16Filled,
TextFont16Regular,
TextGrammarWand16Filled,
TextGrammarWand16Regular,
TextItalic16Filled,
TextItalic16Regular,
TextSortAscending16Filled,
TextSortAscending16Regular,
TextSortDescending16Filled,
TextSortDescending16Regular,
TextStrikethroughS16Filled,
TextStrikethroughS16Regular,
TextUnderline16Filled,
TextUnderline16Regular,
ThumbLike16Filled,
ThumbLike16Regular,
TicketDiagonal16Filled,
TicketDiagonal16Regular,
Timer16Filled,
Timer16Regular,
ToggleLeft16Filled,
ToggleLeft16Regular,
ToggleRight16Filled,
ToggleRight16Regular,
Toolbox16Filled,
Toolbox16Regular,
Translate16Regular,
Trophy16Filled,
Trophy16Regular,
Tv16Filled,
Tv16Regular,
TvUsb16Filled,
TvUsb16Regular,
Vault16Filled,
Vault16Regular,
VehicleBicycle16Filled,
VehicleBicycle16Regular,
VehicleBus16Filled,
VehicleBus16Regular,
VehicleCab16Filled,
VehicleCab16Regular,
VehicleCar16Filled,
VehicleCar16Regular,
VehicleShip16Filled,
VehicleShip16Regular,
VehicleSubway16Filled,
VehicleSubway16Regular,
VehicleTruck16Filled,
VehicleTruck16Regular,
Video16Filled,
Video16Regular,
VideoPerson16Filled,
VideoPerson16Regular,
VideoPersonCall16Filled,
VideoPersonCall16Regular,
VideoProhibited16Filled,
VideoProhibited16Regular,
Voicemail16Filled,
Voicemail16Regular,
Wand16Filled,
Wand16Regular,
Warning16Filled,
Warning16Regular,
WeatherMoon16Filled,
WeatherMoon16Regular,
WeatherMoonOff16Filled,
WeatherMoonOff16Regular,
WindowDevTools16Filled,
WindowDevTools16Regular,
WindowNew16Filled,
WindowNew16Regular,
WindowShield16Filled,
WindowShield16Regular,
Wrench16Filled,
Wrench16Regular,

} from "@fluentui/react-icons";

function App() {
	return (
		<div>
			<Accessibility16Filled/>
<Accessibility16Regular/>
<Add16Filled/>
<Add16Regular/>
<AddCircle16Filled/>
<AddCircle16Regular/>
<AddSquareMultiple16Filled/>
<AddSquareMultiple16Regular/>
<AddSubtractCircle16Filled/>
<AddSubtractCircle16Regular/>
<AirplaneTakeOff16Filled/>
<AirplaneTakeOff16Regular/>
<Alert16Filled/>
<Alert16Regular/>
<AlertOff16Filled/>
<AlertOff16Regular/>
<AlertUrgent16Filled/>
<AlertUrgent16Regular/>
<AlignBottom16Filled/>
<AlignBottom16Regular/>
<AlignCenterHorizontal16Filled/>
<AlignCenterHorizontal16Regular/>
<AlignCenterVertical16Filled/>
<AlignCenterVertical16Regular/>
<AlignLeft16Filled/>
<AlignLeft16Regular/>
<AlignRight16Filled/>
<AlignRight16Regular/>
<AlignTop16Filled/>
<AlignTop16Regular/>
<AnimalRabbit16Filled/>
<AnimalRabbit16Regular/>
<AnimalTurtle16Filled/>
<AnimalTurtle16Regular/>
<ApprovalsApp16Filled/>
<ApprovalsApp16Regular/>
<Apps16Filled/>
<Apps16Regular/>
<AppsAddIn16Filled/>
<AppsAddIn16Regular/>
<Archive16Filled/>
<Archive16Regular/>
<ArrowBounce16Filled/>
<ArrowBounce16Regular/>
<ArrowCircleDownRight16Filled/>
<ArrowCircleDownRight16Regular/>
<ArrowCircleUp16Filled/>
<ArrowCircleUp16Regular/>
<ArrowCurveDownLeft16Filled/>
<ArrowCurveDownLeft16Regular/>
<ArrowDown16Filled/>
<ArrowDown16Regular/>
<ArrowDownLeft16Filled/>
<ArrowDownLeft16Regular/>
<ArrowDownload16Filled/>
<ArrowDownload16Regular/>
<ArrowForward16Filled/>
<ArrowForward16Regular/>
<ArrowHookDownLeft16Filled/>
<ArrowHookDownLeft16Regular/>
<ArrowHookDownRight16Filled/>
<ArrowHookDownRight16Regular/>
<ArrowHookUpLeft16Filled/>
<ArrowHookUpLeft16Regular/>
<ArrowHookUpRight16Filled/>
<ArrowHookUpRight16Regular/>
<ArrowMaximize16Filled/>
<ArrowMaximize16Regular/>
<ArrowMinimize16Filled/>
<ArrowMinimize16Regular/>
<ArrowRepeatAll16Filled/>
<ArrowRepeatAll16Regular/>
<ArrowRepeatAllOff16Filled/>
<ArrowRepeatAllOff16Regular/>
<ArrowReply16Filled/>
<ArrowReply16Regular/>
<ArrowReplyAll16Filled/>
<ArrowReplyAll16Regular/>
<ArrowReplyDown16Filled/>
<ArrowReplyDown16Regular/>
<ArrowRight16Filled/>
<ArrowRight16Regular/>
<ArrowStepBack16Filled/>
<ArrowStepBack16Regular/>
<ArrowStepIn16Filled/>
<ArrowStepIn16Regular/>
<ArrowStepOut16Filled/>
<ArrowStepOut16Regular/>
<ArrowStepOver16Filled/>
<ArrowStepOver16Regular/>
<ArrowSync16Filled/>
<ArrowSync16Regular/>
<ArrowSyncCircle16Filled/>
<ArrowSyncCircle16Regular/>
<ArrowTrending16Filled/>
<ArrowTrending16Regular/>
<ArrowUndo16Filled/>
<ArrowUndo16Regular/>
<ArrowUpLeft16Filled/>
<ArrowUpLeft16Regular/>
<ArrowUpRight16Filled/>
<ArrowUpRight16Regular/>
<ArrowUpload16Filled/>
<ArrowUpload16Regular/>
<Attach16Filled/>
<Attach16Regular/>
<Backpack16Filled/>
<Backpack16Regular/>
<Balloon16Filled/>
<Balloon16Regular/>
<Beach16Filled/>
<Beach16Regular/>
<Beaker16Filled/>
<Beaker16Regular/>
<Bed16Filled/>
<Bed16Regular/>
<Block16Filled/>
<Block16Regular/>
<Blur16Filled/>
<Blur16Regular/>
<Board16Filled/>
<Board16Regular/>
<BoardSplit16Filled/>
<BoardSplit16Regular/>
<BookNumber16Filled/>
<BookNumber16Regular/>
<Bookmark16Filled/>
<Bookmark16Regular/>
<BranchCompare16Filled/>
<BranchCompare16Regular/>
<BranchFork16Filled/>
<BranchFork16Regular/>
<BriefcaseOff16Filled/>
<BriefcaseOff16Regular/>
<Bug16Filled/>
<Bug16Regular/>
<Building16Filled/>
<Building16Regular/>
<BuildingBank16Filled/>
<BuildingBank16Regular/>
<BuildingBankLink16Filled/>
<BuildingBankLink16Regular/>
<BuildingShop16Filled/>
<BuildingShop16Regular/>
<BuildingSkyscraper16Filled/>
<BuildingSkyscraper16Regular/>
<CalendarCancel16Filled/>
<CalendarCancel16Regular/>
<CalendarCheckmark16Filled/>
<CalendarCheckmark16Regular/>
<CalendarClock16Filled/>
<CalendarClock16Regular/>
<CalendarEdit16Filled/>
<CalendarEdit16Regular/>
<CalendarEmpty16Filled/>
<CalendarEmpty16Regular/>
<CalendarLtr16Filled/>
<CalendarLtr16Regular/>
<CalendarMail16Filled/>
<CalendarMail16Regular/>
<CalendarQuestionMark16Filled/>
<CalendarQuestionMark16Regular/>
<CalendarReply16Filled/>
<CalendarReply16Regular/>
<CalendarRtl16Filled/>
<CalendarRtl16Regular/>
<CalendarSync16Filled/>
<CalendarSync16Regular/>
<CalendarToday16Filled/>
<CalendarToday16Regular/>
<CalendarWorkWeek16Filled/>
<CalendarWorkWeek16Regular/>
<Call16Filled/>
<Call16Regular/>
<CallForward16Filled/>
<CallForward16Regular/>
<CallInbound16Filled/>
<CallInbound16Regular/>
<CallMissed16Filled/>
<CallMissed16Regular/>
<CallOutbound16Filled/>
<CallOutbound16Regular/>
<CallPark16Filled/>
<CallPark16Regular/>
<CallProhibited16Filled/>
<CallProhibited16Regular/>
<Camera16Filled/>
<Camera16Regular/>
<Caret16Filled/>
<Caret16Regular/>
<CaretDown16Filled/>
<CaretDown16Regular/>
<CaretDownLeft16Filled/>
<CaretDownLeft16Regular/>
<CaretLeft16Filled/>
<CaretLeft16Regular/>
<CaretRight16Filled/>
<CaretRight16Regular/>
<CaretUp16Filled/>
<CaretUp16Regular/>
<Cart16Filled/>
<Cart16Regular/>
<Channel16Filled/>
<Channel16Regular/>
<ChannelAdd16Filled/>
<ChannelAdd16Regular/>
<ChannelAlert16Filled/>
<ChannelAlert16Regular/>
<ChannelArrowLeft16Filled/>
<ChannelArrowLeft16Regular/>
<ChannelDismiss16Filled/>
<ChannelDismiss16Regular/>
<ChannelShare16Filled/>
<ChannelShare16Regular/>
<Chat16Filled/>
<Chat16Regular/>
<CheckboxUnchecked16Filled/>
<CheckboxUnchecked16Regular/>
<Checkmark16Filled/>
<Checkmark16Regular/>
<CheckmarkCircle16Filled/>
<CheckmarkCircle16Regular/>
<CheckmarkLock16Filled/>
<CheckmarkLock16Regular/>
<CheckmarkUnderlineCircle16Filled/>
<CheckmarkUnderlineCircle16Regular/>
<ChevronDoubleUp16Filled/>
<ChevronDoubleUp16Regular/>
<ChevronDown16Filled/>
<ChevronDown16Regular/>
<ChevronLeft16Filled/>
<ChevronLeft16Regular/>
<ChevronRight16Filled/>
<ChevronRight16Regular/>
<ChevronUp16Filled/>
<ChevronUp16Regular/>
<Circle16Filled/>
<Circle16Regular/>
<City16Filled/>
<City16Regular/>
<Classification16Filled/>
<Classification16Regular/>
<Clipboard16Filled/>
<Clipboard16Regular/>
<ClipboardArrowRight16Filled/>
<ClipboardArrowRight16Regular/>
<ClipboardCode16Filled/>
<ClipboardCode16Regular/>
<ClipboardLetter16Filled/>
<ClipboardLetter16Regular/>
<ClipboardLink16Filled/>
<ClipboardLink16Regular/>
<ClipboardPaste16Filled/>
<ClipboardPaste16Regular/>
<Clock16Filled/>
<Clock16Regular/>
<ClosedCaption16Filled/>
<ClosedCaption16Regular/>
<ClosedCaptionOff16Filled/>
<ClosedCaptionOff16Regular/>
<Cloud16Filled/>
<Cloud16Regular/>
<CloudBackup16Filled/>
<CloudBackup16Regular/>
<CloudDownload16Filled/>
<CloudDownload16Regular/>
<CloudOff16Filled/>
<CloudOff16Regular/>
<CloudSync16Filled/>
<CloudSync16Regular/>
<CloudSyncComplete16Filled/>
<CloudSyncComplete16Regular/>
<ColorLine16Filled/>
<ColorLine16Regular/>
<ColorLineAccent16Regular/>
<Comment16Filled/>
<Comment16Regular/>
<CommentAdd16Filled/>
<CommentAdd16Regular/>
<CommentArrowLeft16Filled/>
<CommentArrowLeft16Regular/>
<CommentArrowRight16Filled/>
<CommentArrowRight16Regular/>
<CommentCheckmark16Filled/>
<CommentCheckmark16Regular/>
<CommentMention16Filled/>
<CommentMention16Regular/>
<CommentMultiple16Filled/>
<CommentMultiple16Regular/>
<CommentOff16Filled/>
<CommentOff16Regular/>
<Communication16Filled/>
<Communication16Regular/>
<CompassNorthwest16Filled/>
<CompassNorthwest16Regular/>
<Compose16Filled/>
<Compose16Regular/>
<ConferenceRoom16Filled/>
<ConferenceRoom16Regular/>
<Connector16Filled/>
<Connector16Regular/>
<ContactCardGroup16Filled/>
<ContactCardGroup16Regular/>
<ContentSettings16Filled/>
<ContentSettings16Regular/>
<Copy16Filled/>
<Copy16Regular/>
<CopyArrowRight16Filled/>
<CopyArrowRight16Regular/>
<Cube16Filled/>
<Cube16Regular/>
<CurrencyDollarEuro16Filled/>
<CurrencyDollarEuro16Regular/>
<CurrencyDollarRupee16Filled/>
<CurrencyDollarRupee16Regular/>
<CursorHover16Filled/>
<CursorHover16Regular/>
<CursorHoverOff16Filled/>
<CursorHoverOff16Regular/>
<Delete16Filled/>
<Delete16Regular/>
<Dentist16Filled/>
<Dentist16Regular/>
<DesignIdeas16Filled/>
<DesignIdeas16Regular/>
<Desktop16Filled/>
<Desktop16Regular/>
<DesktopArrowRight16Filled/>
<DesktopArrowRight16Regular/>
<DesktopMac16Filled/>
<DesktopMac16Regular/>
<DesktopPulse16Filled/>
<DesktopPulse16Regular/>
<Dismiss16Filled/>
<Dismiss16Regular/>
<DismissCircle16Filled/>
<DismissCircle16Regular/>
<DismissSquareMultiple16Filled/>
<DismissSquareMultiple16Regular/>
<DockPanelLeft16Filled/>
<DockPanelLeft16Regular/>
<DockPanelRight16Filled/>
<DockPanelRight16Regular/>
<Doctor16Filled/>
<Doctor16Regular/>
<Document16Filled/>
<Document16Regular/>
<DocumentAdd16Filled/>
<DocumentAdd16Regular/>
<DocumentArrowLeft16Filled/>
<DocumentArrowLeft16Regular/>
<DocumentCatchUp16Filled/>
<DocumentCatchUp16Regular/>
<DocumentCopy16Filled/>
<DocumentCopy16Regular/>
<DocumentEdit16Filled/>
<DocumentEdit16Regular/>
<DocumentError16Filled/>
<DocumentError16Regular/>
<DocumentFooter16Filled/>
<DocumentFooter16Regular/>
<DocumentHeader16Filled/>
<DocumentHeader16Regular/>
<DocumentHeaderArrowDown16Filled/>
<DocumentHeaderArrowDown16Regular/>
<DocumentHeaderFooter16Filled/>
<DocumentHeaderFooter16Regular/>
<DocumentPdf16Filled/>
<DocumentPdf16Regular/>
<DocumentQuestionMark16Filled/>
<DocumentQuestionMark16Regular/>
<DocumentRibbon16Filled/>
<DocumentRibbon16Regular/>
<DoorArrowLeft16Filled/>
<DoorArrowLeft16Regular/>
<Drafts16Filled/>
<Drafts16Regular/>
<DrinkBeer16Filled/>
<DrinkBeer16Regular/>
<DrinkCoffee16Filled/>
<DrinkCoffee16Regular/>
<DrinkMargarita16Filled/>
<DrinkMargarita16Regular/>
<DrinkWine16Filled/>
<DrinkWine16Regular/>
<Drop16Filled/>
<Drop16Regular/>
<Dumbbell16Filled/>
<Dumbbell16Regular/>
<Earth16Filled/>
<Earth16Regular/>
<Edit16Filled/>
<Edit16Regular/>
<EditOff16Filled/>
<EditOff16Regular/>
<Emoji16Filled/>
<Emoji16Regular/>
<EmojiAdd16Filled/>
<EmojiAdd16Regular/>
<ErrorCircle16Filled/>
<ErrorCircle16Regular/>
<EyeShow16Filled/>
<EyeShow16Regular/>
<EyeTrackingOff16Filled/>
<EyeTrackingOff16Regular/>
<EyeTrackingOn16Filled/>
<EyeTrackingOn16Regular/>
<FStop16Filled/>
<FStop16Regular/>
<Filter16Filled/>
<Filter16Regular/>
<Flag16Filled/>
<Flag16Regular/>
<FlagOff16Filled/>
<FlagOff16Regular/>
<FlagPride16Filled/>
<Flash16Filled/>
<Flash16Regular/>
<FlashCheckmark16Filled/>
<FlashCheckmark16Regular/>
<Folder16Filled/>
<Folder16Regular/>
<FolderArrowRight16Filled/>
<FolderArrowRight16Regular/>
<FolderArrowUp16Filled/>
<FolderArrowUp16Regular/>
<FolderMail16Filled/>
<FolderMail16Regular/>
<FolderOpen16Filled/>
<FolderOpen16Regular/>
<FolderProhibited16Filled/>
<FolderProhibited16Regular/>
<FolderSwap16Filled/>
<FolderSwap16Regular/>
<FolderSync16Filled/>
<FolderSync16Regular/>
<FolderZip16Filled/>
<FolderZip16Regular/>
<FontSpaceTrackingIn16Filled/>
<FontSpaceTrackingIn16Regular/>
<FontSpaceTrackingOut16Filled/>
<FontSpaceTrackingOut16Regular/>
<FoodEgg16Filled/>
<FoodEgg16Regular/>
<FoodToast16Filled/>
<FoodToast16Regular/>
<Fps3016Filled/>
<Fps3016Regular/>
<Fps6016Filled/>
<Fps6016Regular/>
<Glasses16Filled/>
<Glasses16Regular/>
<GlassesOff16Filled/>
<GlassesOff16Regular/>
<Globe16Filled/>
<Globe16Regular/>
<Grid16Filled/>
<Grid16Regular/>
<Guest16Filled/>
<Guest16Regular/>
<Guitar16Filled/>
<Guitar16Regular/>
<HandLeft16Filled/>
<HandLeft16Regular/>
<HandRight16Filled/>
<HandRight16Regular/>
<Handshake16Filled/>
<Handshake16Regular/>
<HatGraduation16Filled/>
<HatGraduation16Regular/>
<Hd16Filled/>
<Hd16Regular/>
<Headset16Filled/>
<Headset16Regular/>
<Heart16Filled/>
<Heart16Regular/>
<Highlight16Filled/>
<Highlight16Regular/>
<HighlightAccent16Filled/>
<Home16Filled/>
<Home16Regular/>
<HomeCheckmark16Filled/>
<HomeCheckmark16Regular/>
<Image16Filled/>
<Image16Regular/>
<ImageEdit16Filled/>
<ImageEdit16Regular/>
<Important16Filled/>
<Important16Regular/>
<Info16Filled/>
<Info16Regular/>
<InkingTool16Filled/>
<InkingTool16Regular/>
<InkingToolAccent16Filled/>
<InprivateAccount16Filled/>
<InprivateAccount16Regular/>
<Javascript16Filled/>
<Javascript16Regular/>
<Key16Filled/>
<Key16Regular/>
<KeyCommand16Filled/>
<KeyCommand16Regular/>
<KeyboardShift16Filled/>
<KeyboardShift16Regular/>
<Laptop16Filled/>
<Laptop16Regular/>
<LeafOne16Filled/>
<LeafOne16Regular/>
<LeafThree16Filled/>
<LeafThree16Regular/>
<LeafTwo16Filled/>
<LeafTwo16Regular/>
<Library16Filled/>
<Library16Regular/>
<Lightbulb16Filled/>
<Lightbulb16Regular/>
<LightbulbFilament16Filled/>
<LightbulbFilament16Regular/>
<Likert16Filled/>
<Likert16Regular/>
<Link16Filled/>
<Link16Regular/>
<LinkEdit16Filled/>
<LinkEdit16Regular/>
<LinkSquare16Filled/>
<LinkSquare16Regular/>
<List16Filled/>
<List16Regular/>
<LocalLanguage16Filled/>
<LocalLanguage16Regular/>
<Location16Filled/>
<Location16Regular/>
<LocationOff16Filled/>
<LocationOff16Regular/>
<LockClosed16Filled/>
<LockClosed16Regular/>
<Mail16Filled/>
<Mail16Regular/>
<MailAll16Filled/>
<MailAll16Regular/>
<MailDismiss16Filled/>
<MailDismiss16Regular/>
<MailInbox16Filled/>
<MailInbox16Regular/>
<MailInboxAdd16Filled/>
<MailInboxAdd16Regular/>
<MailInboxCheckmark16Filled/>
<MailInboxCheckmark16Regular/>
<MailInboxDismiss16Filled/>
<MailInboxDismiss16Regular/>
<MailProhibited16Filled/>
<MailProhibited16Regular/>
<MailRead16Filled/>
<MailRead16Regular/>
<MailUnread16Filled/>
<MailUnread16Regular/>
<MapDrive16Filled/>
<MapDrive16Regular/>
<MathFormula16Filled/>
<MathFormula16Regular/>
<Maximize16Filled/>
<Maximize16Regular/>
<MeetNow16Filled/>
<MeetNow16Regular/>
<Megaphone16Filled/>
<Megaphone16Regular/>
<Mention16Filled/>
<Mention16Regular/>
<MicOff16Filled/>
<MicOff16Regular/>
<MicOn16Filled/>
<MicOn16Regular/>
<MicProhibited16Filled/>
<MicProhibited16Regular/>
<MicSparkle16Filled/>
<MicSparkle16Regular/>
<Money16Filled/>
<Money16Regular/>
<MoreHorizontal16Filled/>
<MoreHorizontal16Regular/>
<MoreVertical16Filled/>
<MoreVertical16Regular/>
<MoviesAndTv16Filled/>
<MoviesAndTv16Regular/>
<MusicNote216Filled/>
<MusicNote216Regular/>
<MyLocation16Filled/>
<MyLocation16Regular/>
<New16Filled/>
<New16Regular/>
<Next16Filled/>
<Next16Regular/>
<NoteAdd16Filled/>
<NoteAdd16Regular/>
<NumberRow16Filled/>
<NumberRow16Regular/>
<NumberSymbol16Filled/>
<NumberSymbol16Regular/>
<Open16Filled/>
<Open16Regular/>
<OpenFolder16Filled/>
<OpenFolder16Regular/>
<OpenOff16Filled/>
<OpenOff16Regular/>
<Options16Filled/>
<Options16Regular/>
<PageFit16Filled/>
<PageFit16Regular/>
<PaintBrush16Filled/>
<PaintBrush16Regular/>
<PaintBucket16Filled/>
<PaintBucket16Regular/>
<PaneClose16Filled/>
<PaneClose16Regular/>
<PaneOpen16Filled/>
<PaneOpen16Regular/>
<Pause16Filled/>
<Pause16Regular/>
<Payment16Filled/>
<Payment16Regular/>
<People16Filled/>
<People16Regular/>
<PeopleAdd16Filled/>
<PeopleAdd16Regular/>
<PeopleCall16Filled/>
<PeopleCall16Regular/>
<PeopleCommunity16Filled/>
<PeopleCommunity16Regular/>
<PeopleError16Filled/>
<PeopleError16Regular/>
<PeopleProhibited16Filled/>
<PeopleProhibited16Regular/>
<PeopleSwap16Filled/>
<PeopleSwap16Regular/>
<PeopleTeam16Filled/>
<PeopleTeam16Regular/>
<Person16Filled/>
<Person16Regular/>
<PersonAdd16Filled/>
<PersonAdd16Regular/>
<PersonArrowRight16Filled/>
<PersonArrowRight16Regular/>
<PersonAvailable16Filled/>
<PersonAvailable16Regular/>
<PersonBoard16Filled/>
<PersonBoard16Regular/>
<PersonCall16Filled/>
<PersonCall16Regular/>
<PersonClock16Filled/>
<PersonClock16Regular/>
<PersonDelete16Filled/>
<PersonDelete16Regular/>
<PersonMail16Filled/>
<PersonMail16Regular/>
<PersonProhibited16Filled/>
<PersonProhibited16Regular/>
<PersonQuestionMark16Filled/>
<PersonQuestionMark16Regular/>
<PersonSupport16Filled/>
<PersonSupport16Regular/>
<PersonSwap16Filled/>
<PersonSwap16Regular/>
<PhoneDesktop16Filled/>
<PhoneDesktop16Regular/>
<PhoneLaptop16Filled/>
<PhoneLaptop16Regular/>
<PhoneSpanIn16Filled/>
<PhoneSpanIn16Regular/>
<PhoneSpanOut16Filled/>
<PhoneSpanOut16Regular/>
<PictureInPicture16Filled/>
<PictureInPicture16Regular/>
<Pin16Filled/>
<Pin16Regular/>
<PinOff16Filled/>
<PinOff16Regular/>
<PlayCircle16Filled/>
<PlayCircle16Regular/>
<Premium16Filled/>
<Premium16Regular/>
<PresenceAvailable16Filled/>
<PresenceAvailable16Regular/>
<PresenceAway16Filled/>
<PresenceBlocked16Regular/>
<PresenceBusy16Filled/>
<PresenceDnd16Filled/>
<PresenceDnd16Regular/>
<PresenceOffline16Regular/>
<PresenceOof16Regular/>
<PresenceUnknown16Regular/>
<PreviewLink16Filled/>
<PreviewLink16Regular/>
<Previous16Filled/>
<Previous16Regular/>
<ProhibitedMultiple16Filled/>
<ProhibitedMultiple16Regular/>
<ProtocolHandler16Filled/>
<ProtocolHandler16Regular/>
<PuzzleCube16Filled/>
<PuzzleCube16Regular/>
<Question16Filled/>
<Question16Regular/>
<QuestionCircle16Filled/>
<QuestionCircle16Regular/>
<RatingMature16Filled/>
<RatingMature16Regular/>
<ReOrder16Filled/>
<ReOrder16Regular/>
<ReOrderDotsHorizontal16Filled/>
<ReOrderDotsHorizontal16Regular/>
<ReOrderDotsVertical16Filled/>
<ReOrderDotsVertical16Regular/>
<ReadAloud16Filled/>
<ReadAloud16Regular/>
<ReadingList16Filled/>
<ReadingList16Regular/>
<ReadingListAdd16Filled/>
<ReadingListAdd16Regular/>
<Record16Filled/>
<Record16Regular/>
<Remote16Filled/>
<Remote16Regular/>
<Rename16Filled/>
<Rename16Regular/>
<ResizeLarge16Filled/>
<ResizeLarge16Regular/>
<ResizeSmall16Filled/>
<ResizeSmall16Regular/>
<Restore16Filled/>
<Restore16Regular/>
<Reward16Filled/>
<Reward16Regular/>
<Ribbon16Filled/>
<Ribbon16Regular/>
<Rocket16Filled/>
<Rocket16Regular/>
<Ruler16Filled/>
<Ruler16Regular/>
<Run16Filled/>
<Run16Regular/>
<Savings16Filled/>
<Savings16Regular/>
<ScaleFit16Filled/>
<ScaleFit16Regular/>
<Search16Filled/>
<Search16Regular/>
<SearchVisual16Filled/>
<SearchVisual16Regular/>
<Send16Filled/>
<Send16Regular/>
<SerialPort16Filled/>
<SerialPort16Regular/>
<SetTopStack16Filled/>
<SetTopStack16Regular/>
<Settings16Filled/>
<Settings16Regular/>
<ShapeExclude16Filled/>
<ShapeExclude16Regular/>
<ShapeIntersect16Filled/>
<ShapeIntersect16Regular/>
<ShapeSubtract16Filled/>
<ShapeSubtract16Regular/>
<ShapeUnion16Filled/>
<ShapeUnion16Regular/>
<Shapes16Filled/>
<Shapes16Regular/>
<ShareScreenStop16Filled/>
<ShareScreenStop16Regular/>
<Shield16Filled/>
<Shield16Regular/>
<ShieldCheckmark16Filled/>
<ShieldCheckmark16Regular/>
<ShieldDismiss16Filled/>
<ShieldDismiss16Regular/>
<ShieldKeyhole16Filled/>
<ShieldKeyhole16Regular/>
<Shifts16Filled/>
<Shifts16Regular/>
<Signature16Filled/>
<Signature16Regular/>
<Signed16Filled/>
<Signed16Regular/>
<Sim16Filled/>
<Sim16Regular/>
<SlideText16Filled/>
<SlideText16Regular/>
<Snooze16Filled/>
<Snooze16Regular/>
<Speaker016Filled/>
<Speaker016Regular/>
<Speaker116Filled/>
<Speaker116Regular/>
<Speaker216Filled/>
<Speaker216Regular/>
<SpeakerEdit16Filled/>
<SpeakerEdit16Regular/>
<SpeakerMute16Filled/>
<SpeakerMute16Regular/>
<SpeakerOff16Filled/>
<SpeakerOff16Regular/>
<SplitHorizontal16Filled/>
<SplitHorizontal16Regular/>
<SplitVertical16Filled/>
<SplitVertical16Regular/>
<Sport16Filled/>
<Sport16Regular/>
<SquareArrowForward16Filled/>
<SquareArrowForward16Regular/>
<Star16Filled/>
<Star16Regular/>
<StarAdd16Filled/>
<StarAdd16Regular/>
<StarHalf16Filled/>
<StarOff16Filled/>
<StarOff16Regular/>
<StarOneQuarter16Filled/>
<StarProhibited16Filled/>
<StarProhibited16Regular/>
<StarThreeQuarter16Filled/>
<Status16Filled/>
<Status16Regular/>
<Stop16Filled/>
<Stop16Regular/>
<StoreMicrosoft16Filled/>
<StoreMicrosoft16Regular/>
<StrikethroughGaNa16Filled/>
<StrikethroughGaNa16Regular/>
<Subtract16Filled/>
<Subtract16Regular/>
<SubtractSquareMultiple16Filled/>
<SubtractSquareMultiple16Regular/>
<Symbols16Filled/>
<Symbols16Regular/>
<SyncOff16Filled/>
<SyncOff16Regular/>
<Tab16Filled/>
<Tab16Regular/>
<TabDesktopArrowClockwise16Filled/>
<TabDesktopArrowClockwise16Regular/>
<TabDesktopImage16Filled/>
<TabDesktopImage16Regular/>
<TabInPrivate16Filled/>
<TabInPrivate16Regular/>
<Table16Filled/>
<Table16Regular/>
<TableSimple16Filled/>
<TableSimple16Regular/>
<Tag16Filled/>
<Tag16Regular/>
<TagQuestionMark16Filled/>
<TagQuestionMark16Regular/>
<Target16Filled/>
<Target16Regular/>
<TargetEdit16Filled/>
<TargetEdit16Regular/>
<Tent16Filled/>
<Tent16Regular/>
<TetrisApp16Filled/>
<TetrisApp16Regular/>
<TextBold16Filled/>
<TextBold16Regular/>
<TextBulletListSquareWarning16Filled/>
<TextBulletListSquareWarning16Regular/>
<TextBulletListTree16Filled/>
<TextBulletListTree16Regular/>
<TextColor16Filled/>
<TextColor16Regular/>
<TextColorAccent16Regular/>
<TextField16Filled/>
<TextField16Regular/>
<TextFont16Filled/>
<TextFont16Regular/>
<TextGrammarWand16Filled/>
<TextGrammarWand16Regular/>
<TextItalic16Filled/>
<TextItalic16Regular/>
<TextSortAscending16Filled/>
<TextSortAscending16Regular/>
<TextSortDescending16Filled/>
<TextSortDescending16Regular/>
<TextStrikethroughS16Filled/>
<TextStrikethroughS16Regular/>
<TextUnderline16Filled/>
<TextUnderline16Regular/>
<ThumbLike16Filled/>
<ThumbLike16Regular/>
<TicketDiagonal16Filled/>
<TicketDiagonal16Regular/>
<Timer16Filled/>
<Timer16Regular/>
<ToggleLeft16Filled/>
<ToggleLeft16Regular/>
<ToggleRight16Filled/>
<ToggleRight16Regular/>
<Toolbox16Filled/>
<Toolbox16Regular/>
<Translate16Regular/>
<Trophy16Filled/>
<Trophy16Regular/>
<Tv16Filled/>
<Tv16Regular/>
<TvUsb16Filled/>
<TvUsb16Regular/>
<Vault16Filled/>
<Vault16Regular/>
<VehicleBicycle16Filled/>
<VehicleBicycle16Regular/>
<VehicleBus16Filled/>
<VehicleBus16Regular/>
<VehicleCab16Filled/>
<VehicleCab16Regular/>
<VehicleCar16Filled/>
<VehicleCar16Regular/>
<VehicleShip16Filled/>
<VehicleShip16Regular/>
<VehicleSubway16Filled/>
<VehicleSubway16Regular/>
<VehicleTruck16Filled/>
<VehicleTruck16Regular/>
<Video16Filled/>
<Video16Regular/>
<VideoPerson16Filled/>
<VideoPerson16Regular/>
<VideoPersonCall16Filled/>
<VideoPersonCall16Regular/>
<VideoProhibited16Filled/>
<VideoProhibited16Regular/>
<Voicemail16Filled/>
<Voicemail16Regular/>
<Wand16Filled/>
<Wand16Regular/>
<Warning16Filled/>
<Warning16Regular/>
<WeatherMoon16Filled/>
<WeatherMoon16Regular/>
<WeatherMoonOff16Filled/>
<WeatherMoonOff16Regular/>
<WindowDevTools16Filled/>
<WindowDevTools16Regular/>
<WindowNew16Filled/>
<WindowNew16Regular/>
<WindowShield16Filled/>
<WindowShield16Regular/>
<Wrench16Filled/>
<Wrench16Regular/>
        </div >
    );
}

const rootElement = document.getElementById("root");
render(<App />, rootElement);