// AUTO-GENERATED by scripts/generate-icon-sizes.mjs — do not edit by hand.
// Regenerate with: npm run generate:data (inside packages/eslint-plugin-react-icons).
//
// Source of truth: @fluentui/react-icons metadata.json (icon "type" field).

/**
 * Pixel sizes used by "sized" Fluent icon variants (e.g. `AccessTime24Filled`).
 * All Fluent icon sizes are two digits; a sized export name embeds one of these
 * immediately before its variant suffix.
 */
export const SIZED_ICON_SIZES: readonly number[] = [10, 12, 16, 20, 24, 28, 32, 48];

/**
 * "resizable" icon names that syntactically look "sized" because a product name
 * ends in a two-digit number matching a real size (e.g. `Battery10Regular`, where
 * "10" is a battery level, not a size). These must NOT be flagged as sized.
 */
export const RESIZABLE_COLLISIONS: readonly string[] = [
  'Battery10Filled',
  'Battery10Regular',
  'BatteryCharge10Filled',
  'BatteryCharge10Regular',
  'Fps120Filled',
  'Fps120Regular',
  'Fps124Filled',
  'Fps124Regular',
  'SkipBack10Filled',
  'SkipBack10Regular',
  'SkipForward10Filled',
  'SkipForward10Regular',
  'Timer10Filled',
  'Timer10Regular',
];
