// @ts-check
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

const fs = require('node:fs');
const { join } = require('node:path');

const PACKAGE_ROOT = join(__dirname, '..');
const JSON_SOURCE = join(PACKAGE_ROOT, 'src', 'common', 'fileTypeIconMap.json');
const GENERATED_OUTPUT = join(PACKAGE_ROOT, 'src', 'common', 'fileTypeIconMap.generated.ts');

/**
 * Packs the declarative `icon -> extensions[]` map into the minimal runtime string.
 *
 * Only icons that actually map to one or more file extensions are emitted; icons
 * without extensions (i.e. `null`, e.g. `folder`, `album`) are resolved via
 * {@link FileIconType} constants at runtime and therefore do not need to ship in
 * the extension table.
 *
 * Format: `icon:ext,ext;icon:ext` — `;` separates groups, `:` separates the icon
 * name from its extensions, `,` separates extensions. None of these delimiters
 * appear in icon names or extensions.
 *
 * @param {Record<string, string[] | null>} map
 * @returns {string}
 */
function pack(map) {
  return Object.keys(map)
    .sort()
    .filter((icon) => map[icon] != null && map[icon].length > 0)
    .map((icon) => `${icon}:${map[icon].join(',')}`)
    .join(';');
}

/**
 * Renders the generated TypeScript module for a given packed string.
 *
 * @param {string} packed
 * @returns {string}
 */
function renderModule(packed) {
  return `// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// AUTO-GENERATED by scripts/generateFileTypeIconMap.js from src/common/fileTypeIconMap.json.
// Do not edit this file manually. Run \`npm run generate\` to regenerate it.

/**
 * Minimal packed \`icon name\`->\`extensions\` table.
 *
 * Format: \`icon:ext,ext;icon:ext\`. Decoded lazily into an
 * \`extension -> icon name\` lookup by {@link getFileTypeIconExtensionMap}.
 */
const PACKED_FILE_TYPE_ICON_MAP =
  '${packed}';

let _extensionToIconName: { [extension: string]: string } | undefined;

/**
 * Returns the \`extension\`->\`icon name\` lookup table, decoding the packed
 * string on first use and caching the result for subsequent calls.
 */
export function getFileTypeIconExtensionMap(): Readonly<{ [extension: string]: string }> {
  if (!_extensionToIconName) {
    _extensionToIconName = {};
    for (const group of PACKED_FILE_TYPE_ICON_MAP.split(';')) {
      const [iconName, extensions] = group.split(':');
      for (const extension of extensions.split(',')) {
        _extensionToIconName[extension] = iconName;
      }
    }
  }
  return _extensionToIconName;
}
`;
}

/**
 * Reads the JSON source of truth.
 *
 * @returns {Record<string, string[] | null>}
 */
function readSource() {
  return JSON.parse(fs.readFileSync(JSON_SOURCE, 'utf8'));
}

/**
 * Generates the packed module content from the JSON source of truth.
 *
 * @returns {string}
 */
function generate() {
  return renderModule(pack(readSource()));
}

function main() {
  const content = generate();
  fs.writeFileSync(GENERATED_OUTPUT, content);
  console.log(`Generated ${GENERATED_OUTPUT}`);
}

main();
