// @ts-check
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

const fs = require('node:fs');
const { join } = require('node:path');

const PACKAGE_ROOT = join(__dirname, '..');
const JSON_SOURCE = join(PACKAGE_ROOT, 'src', 'fileIconTypes.json');
const GENERATED_OUTPUT = join(PACKAGE_ROOT, 'src', 'fileIconTypes.generated.ts');

/**
 * @typedef {{ value: number; name: string; icon: string | null }} FileIconTypeEntry
 */

/**
 * Reads the declarative file icon type source of truth. Each entry explicitly declares its
 * numeric `value` (so the public `FileIconType` numbering does not depend on array order),
 * its `name` (the enum member / object key), and its `icon` base name (or `null` when the
 * member has no dedicated icon and falls back to the generic file icon at runtime).
 *
 * @returns {FileIconTypeEntry[]}
 */
function readSource() {
  return JSON.parse(fs.readFileSync(JSON_SOURCE, 'utf8'));
}

/**
 * Validates and returns the entries sorted by their explicit numeric `value`. Throws if the
 * declared values are not unique positive integers forming a contiguous 1..N sequence, since
 * the positional lookup relies on a dense index.
 *
 * @param {FileIconTypeEntry[]} entries
 * @returns {FileIconTypeEntry[]}
 */
function normalize(entries) {
  const sorted = [...entries].sort((a, b) => a.value - b.value);

  sorted.forEach((entry, index) => {
    const expected = index + 1;
    if (entry.value !== expected) {
      throw new Error(
        `fileIconTypes.json: expected a contiguous 1-based "value" sequence, but found ` +
          `${entry.value} ("${entry.name}") where ${expected} was expected. ` +
          `Values must be unique positive integers from 1..N.`,
      );
    }
  });

  return sorted;
}

/**
 * Renders the generated TypeScript module from the (validated, sorted) entries.
 *
 * @param {FileIconTypeEntry[]} entries
 * @returns {string}
 */
function renderModule(entries) {
  // `member: value` entries for the const object.
  const constEntries = entries.map((entry) => `  ${entry.name}: ${entry.value},`).join('\n');

  // Positional `value -> icon base name` lookup. Index 0 is unused (values start at 1);
  // members with a `null` icon emit '' and fall back to the generic file icon at runtime.
  const lookupEntries = ["  '', // 0 (unused)"]
    .concat(entries.map((entry) => `  '${entry.icon ?? ''}', // ${entry.value} ${entry.name}`))
    .join('\n');

  return `// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// AUTO-GENERATED by scripts/generateFileIconTypes.js from src/fileIconTypes.json.
// Do not edit this file manually. Run \`npm run generate\` to regenerate it.

/**
 * Enumerates special file type icons that do not map to any file extensions.
 * For example, the 'pptx' icon maps to the extensions 'ppt', 'pptm', 'pptx',
 * but the 'folder' icon does not map to any extensions and should be obtained
 * via this enum.
 *
 * Implemented as a \`const\` object (rather than a TypeScript \`enum\`) so it does not
 * emit a runtime reverse-mapping. The merged \`FileIconType\` type below lets it be
 * used as both a value (\`FileIconType.folder\`) and a type (\`type: FileIconType\`),
 * preserving the ergonomics of the previous \`enum\`. Values start at 1 so they evaluate
 * as truthy.
 */
export const FileIconType = {
${constEntries}
} as const;

export type FileIconType = (typeof FileIconType)[keyof typeof FileIconType];

/**
 * Numeric input form of {@link FileIconType}, accepted by the \`type\` prop / option.
 * Structurally identical to \`FileIconType\` (\`1 | 2 | … | N\`); kept as a named alias
 * for API stability and call-site readability.
 */
export type FileIconTypeInput = FileIconType;

/**
 * Icon base name for each numeric {@link FileIconType} value, positionally indexed by
 * that value (index 0 is unused since values start at 1). Empty entries fall back to the
 * generic file icon at runtime.
 */
export const TYPE_TO_ICON_NAME: ReadonlyArray<string> = [
${lookupEntries}
];
`;
}

/**
 * Generates the module content from the JSON source of truth.
 *
 * @returns {string}
 */
function generate() {
  return renderModule(normalize(readSource()));
}

function main() {
  const content = generate();
  fs.writeFileSync(GENERATED_OUTPUT, content);
  console.log(`Generated ${GENERATED_OUTPUT}`);
}

main();
