name: Bundle Size Baseline

on:
  push:
    branches:
      - main
    paths:
      - 'packages/react-icons/**'
      # Icons changes can affect the bundle size so we wanna run the baseline update here as well
      - 'assets/**'

jobs:
  bundle-size-baseline:
    if: ${{ github.repository_owner == 'microsoft' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - run: npm ci

      - name: Prepare bundle size report
        run: |
          npx nx run-many -t bundle-size --nxBail

      - name: Aggregate bundle size report
        run: npx monosize upload-report --branch main --commit-sha ${{ github.sha }}

      - name: Upload report artifact
        uses: actions/upload-artifact@v7
        with:
          name: monosize-report
          path: dist/bundle-size-report.json
          retention-days: 90

