name: Bundle Size Baseline

on:
  push:
    branches:
      - main
    paths:
      - 'packages/react-icons/**'
      # Icons changes can affect the bundle size so we wanna run the baseline update here as well
      - 'assets/**'

jobs:
  bundle-size-baseline:
    if: ${{ github.repository_owner == 'microsoft' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: corepack enable

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.x
          cache: 'yarn'

      - run: yarn install --immutable

      - name: Prepare bundle size report
        run: |
          yarn nx run-many -t bundle-size --nxBail

      - name: Aggregate bundle size report
        run: yarn monosize upload-report --branch main --commit-sha ${{ github.sha }}

      - name: Upload report artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: monosize-report
          path: dist/bundle-size-report.json
          retention-days: 90
