name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # TODO(nicroma) set environ for 1.1.$GITHUB_RUN_NUMBER

    steps:
    - uses: actions/checkout@v2

    - name: Use Node 11
      uses: actions/setup-node@v1
      with:
        node-version: 11.x

    - run: npm install
      working-directory: importer

    # TODO(nicroma) break these into multiple jobs

    - name: Run generate script
      run: npm run deploy:ios
      working-directory: importer

    - name: Run generate script
      run: npm run deploy:android
      working-directory: importer

    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        # publish
        #  -DvstsAccessToken=$(System.AccessToken)
        arguments: build -DversionName=$(Build.BuildNumber)
        build-root-directory: android
        wrapper-directory: android

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version numbers in README.md
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/1.1.$GITHUB_RUN_NUMBER/g" README.md
        rm README.md.bk

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version numbers in ios/README.md
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/1.1.$GITHUB_RUN_NUMBER/g" ios/README.md
        rm ios/README.md.bk

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version number in Podspec
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/1.1.$GITHUB_RUN_NUMBER/g" ios/FluentIcons.podspec
        rm ios/FluentIcons.podspec.bk

    - name: Config git credentials
      run: git config user.email "flubuild@microsoft.com" && git config user.name "Fluent Build System"

    - name: Commit version number change
      run: |
        git add -A
        git commit -m "Release 1.1.$GITHUB_RUN_NUMBER"

    - name: Tag release
      run: git tag "1.1.$GITHUB_RUN_NUMBER"

    - name: Push release
      run: |
        REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push $REMOTE_REPO HEAD:master --follow-tags --tags
