# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node 11
      uses: actions/setup-node@v1
      with:
        node-version: 11.x

    - run: npm install
      working-directory: importer

    # TODO(nicroma) break these into multiple jobs

    - name: Run generate script
      run: npm run deploy:ios
      working-directory: importer

    - name: Run generate script
      run: npm run deploy:android
      working-directory: importer

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version numbers in README.md
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/1.1.$GITHUB_RUN_NUMBER/g" README.md
        rm README.md.bk

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version numbers in ios/README.md
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/1.1.$GITHUB_RUN_NUMBER/g" ios/README.md
        rm ios/README.md.bk

    # Needs to be "-E" instead of "-r" on macOS
    - name: Replace version number in Podspec
      run: |
        sed -i.bk -r "s/[0-9]+\.[0-9]+\.[0-9]+/1.1.$GITHUB_RUN_NUMBER/g" ios/FluentIcons.podspec
        rm ios/FluentIcons.podspec.bk

    - name: Config git credentials
      run: git config user.email "flubuild@microsoft.com" && git config user.name "Fluent Build System"

    - name: Commit version number change
      run: |
        git add -A
        git commit -m 'Prepare release $(Build.BuildNumber)'

    - name: Tag release
      run: git tag "1.1.$GITHUB_RUN_NUMBER"

    - run: git log
